INSERT INTO "Account"("Id", "Type", "UserName", "Password", "Name", "Phone", "Email", "Status", "IsLock", "ClosedTime", "ClosedBy", "CreatedTime", "CreatedBy", "ModifiedTime", "ModifiedBy", "Deleted", "DeletedTime", "DeletedBy") VALUES ('39F08CFD-8E0D-771B-A2F3-2639A62CA2FA', 0, 'admin', 'E739279CB28CDAFD7373618313803524', '管理员', '', '', 1, 0, '2019-09-29 10:19:21', '00000000-0000-0000-0000-000000000000', '2019-09-29 10:19:21', '00000000-0000-0000-0000-000000000000', '2020-01-14 15:20:04', '39F08CFD-8E0D-771B-A2F3-2639A62CA2FA', 0, '2019-09-29 10:19:21', '00000000-0000-0000-0000-000000000000');
INSERT INTO "Account_Config"("AccountId", "Skin", "Theme", "FontSize") VALUES ('39F08CFD-8E0D-771B-A2F3-2639A62CA2FA', 'pretty', 'default', 'small');
INSERT INTO "Account_Role"("AccountId", "RoleId") VALUES ('39F08CFD-8E0D-771B-A2F3-2639A62CA2FA', '39F08CFD-8DD0-BB54-4544-C2DC43C6CA38');
INSERT INTO "Config"("Type", "Code", "Value") VALUES (0, 'System', '{"title":"NetModular通用权限管理系统","logo":"","copyright":"版权所有：尼古拉斯·老李 | 用代码改变世界 Powered by .Net Core 3.1.0 on Linux","userPage":""}');
INSERT INTO "Config"("Type", "Code", "Value") VALUES (1, 'Admin', '{"auditing":true,"loginLog":true,"defaultPassword":"123456"}');
INSERT INTO "Config"("Type", "Code", "Value") VALUES (0, 'Auth', '{"verifyCode":false,"validate":true,"button":true,"singleAccount":false,"auditing":false,"jwt":{"key":"twAJ$j5##pVc5*y&","issuer":"http://127.0.0.1:6220","audience":"http://127.0.0.1:6220","expires":120,"refreshTokenExpires":7},"loginMode":{"userName":true,"email":true,"userNameOrEmail":true,"phone":true,"weChatScanCode":false,"qq":false,"gitHub":false}}');
INSERT INTO "Config"("Type", "Code", "Value") VALUES (0, 'Component', '{"login":{"defaultAccountType":0,"pageType":"neon","verifyCode":false},"menu":{"uniqueOpened":true},"dialog":{"closeOnClickModal":false,"draggable":false},"list":{"serialNumberName":null},"tabnav":{"enabled":true,"showHome":true,"homeUrl":null,"showIcon":true,"maxOpenCount":20},"toolbar":{"fullscreen":true,"skin":true,"logout":true,"userInfo":true},"customCss":null}');
INSERT INTO "Menu"("Id", "ModuleCode", "Type", "ParentId", "Name", "RouteName", "RouteParams", "RouteQuery", "Url", "Icon", "IconColor", "Level", "Show", "Sort", "Target", "DialogWidth", "DialogHeight", "DialogFullscreen", "Remarks", "CreatedTime", "CreatedBy", "ModifiedTime", "ModifiedBy")  VALUES ('39F3C49B-5FC3-33BE-0FCD-652929D9EA73', '', 2, '00000000-0000-0000-0000-000000000000', '官方文档', '', '', '', 'http://docs.17mkh.com/', 'archives', '', 0, 1, 3, 0, '', '', 1, '', '2020-03-07 08:39:13', '39F08CFD-8E0D-771B-A2F3-2639A62CA2FA', '2020-04-29 19:48:52', '39F08CFD-8E0D-771B-A2F3-2639A62CA2FA');
INSERT INTO "Menu"("Id", "ModuleCode", "Type", "ParentId", "Name", "RouteName", "RouteParams", "RouteQuery", "Url", "Icon", "IconColor", "Level", "Show", "Sort", "Target", "DialogWidth", "DialogHeight", "DialogFullscreen", "Remarks", "CreatedTime", "CreatedBy", "ModifiedTime", "ModifiedBy")  VALUES ('39F3C49B-D757-EA18-E9C4-D9C768F77512', '', 2, '00000000-0000-0000-0000-000000000000', 'GitHub', '', '', '', 'https://github.com/iamoldli/NetModular', 'github', '', 0, 1, 4, 0, '', '', 1, '', '2020-03-07 08:39:43', '39F08CFD-8E0D-771B-A2F3-2639A62CA2FA', '2020-04-29 19:48:52', '39F08CFD-8E0D-771B-A2F3-2639A62CA2FA');
INSERT INTO "Menu"("Id", "ModuleCode", "Type", "ParentId", "Name", "RouteName", "RouteParams", "RouteQuery", "Url", "Icon", "IconColor", "Level", "Show", "Sort", "Target", "DialogWidth", "DialogHeight", "DialogFullscreen", "Remarks", "CreatedTime", "CreatedBy", "ModifiedTime", "ModifiedBy")  VALUES ('39F3C49C-1756-9047-34B5-6DCFADEFE28D', '', 0, '00000000-0000-0000-0000-000000000000', '系统运维', '', '', '', '', 'system', '', 0, 1, 1, -1, '', '', 1, '', '2020-03-07 08:40:00', '39F08CFD-8E0D-771B-A2F3-2639A62CA2FA', '2020-04-29 20:59:15', '39F08CFD-8E0D-771B-A2F3-2639A62CA2FA');
INSERT INTO "Menu"("Id", "ModuleCode", "Type", "ParentId", "Name", "RouteName", "RouteParams", "RouteQuery", "Url", "Icon", "IconColor", "Level", "Show", "Sort", "Target", "DialogWidth", "DialogHeight", "DialogFullscreen", "Remarks", "CreatedTime", "CreatedBy", "ModifiedTime", "ModifiedBy")  VALUES ('39F3C49C-400A-B33D-0C8F-E878AAABA954', '', 0, '00000000-0000-0000-0000-000000000000', '权限管理', '', '', '', '', 'verifycode', '', 0, 1, 0, -1, '', '', 1, '', '2020-03-07 08:40:10', '39F08CFD-8E0D-771B-A2F3-2639A62CA2FA', '2020-04-29 19:48:51', '39F08CFD-8E0D-771B-A2F3-2639A62CA2FA');
INSERT INTO "Menu"("Id", "ModuleCode", "Type", "ParentId", "Name", "RouteName", "RouteParams", "RouteQuery", "Url", "Icon", "IconColor", "Level", "Show", "Sort", "Target", "DialogWidth", "DialogHeight", "DialogFullscreen", "Remarks", "CreatedTime", "CreatedBy", "ModifiedTime", "ModifiedBy")  VALUES ('39F3C49C-8CCC-2A54-DAC7-B5DD6503D91A', 'Admin', 1, '39F3C49C-1756-9047-34B5-6DCFADEFE28D', '配置中心', 'admin_config', '', '', '', 'tools', '', 1, 1, 0, 0, '', '', 1, '', '2020-03-07 08:40:30', '39F08CFD-8E0D-771B-A2F3-2639A62CA2FA', '2020-04-29 20:57:54', '39F08CFD-8E0D-771B-A2F3-2639A62CA2FA');
INSERT INTO "Menu"("Id", "ModuleCode", "Type", "ParentId", "Name", "RouteName", "RouteParams", "RouteQuery", "Url", "Icon", "IconColor", "Level", "Show", "Sort", "Target", "DialogWidth", "DialogHeight", "DialogFullscreen", "Remarks", "CreatedTime", "CreatedBy", "ModifiedTime", "ModifiedBy")  VALUES ('39F3C49C-9EF2-C04B-FC63-5CDC9811C506', 'Admin', 1, '39F3C49C-1756-9047-34B5-6DCFADEFE28D', '缓存清理', 'admin_cache', '', '', '', 'redis', '', 1, 1, 3, 0, '', '', 1, '', '2020-03-07 08:40:34', '39F08CFD-8E0D-771B-A2F3-2639A62CA2FA', '2020-04-29 21:00:24', '39F08CFD-8E0D-771B-A2F3-2639A62CA2FA');
INSERT INTO "Menu"("Id", "ModuleCode", "Type", "ParentId", "Name", "RouteName", "RouteParams", "RouteQuery", "Url", "Icon", "IconColor", "Level", "Show", "Sort", "Target", "DialogWidth", "DialogHeight", "DialogFullscreen", "Remarks", "CreatedTime", "CreatedBy", "ModifiedTime", "ModifiedBy")  VALUES ('39F3C49C-ADF2-D90F-9626-99ACECC76C37', 'Admin', 1, '39F3C49C-1756-9047-34B5-6DCFADEFE28D', '图标预览', 'admin_icon', '', '', '', 'icon', '', 1, 1, 2, 0, '', '', 1, '', '2020-03-07 08:40:38', '39F08CFD-8E0D-771B-A2F3-2639A62CA2FA', '2020-04-29 20:59:57', '39F08CFD-8E0D-771B-A2F3-2639A62CA2FA');
INSERT INTO "Menu"("Id", "ModuleCode", "Type", "ParentId", "Name", "RouteName", "RouteParams", "RouteQuery", "Url", "Icon", "IconColor", "Level", "Show", "Sort", "Target", "DialogWidth", "DialogHeight", "DialogFullscreen", "Remarks", "CreatedTime", "CreatedBy", "ModifiedTime", "ModifiedBy")  VALUES ('39F3C49C-D5DC-90A5-6CC3-B3A0B9040643', 'Admin', 1, '39F3C49C-400A-B33D-0C8F-E878AAABA954', '模块中心', 'admin_module', '', '', '', 'product', '', 1, 1, 0, 0, '', '', 1, '', '2020-03-07 08:40:48', '39F08CFD-8E0D-771B-A2F3-2639A62CA2FA', '2020-06-06 19:20:29', '39F08CFD-8E0D-771B-A2F3-2639A62CA2FA');
INSERT INTO "Menu"("Id", "ModuleCode", "Type", "ParentId", "Name", "RouteName", "RouteParams", "RouteQuery", "Url", "Icon", "IconColor", "Level", "Show", "Sort", "Target", "DialogWidth", "DialogHeight", "DialogFullscreen", "Remarks", "CreatedTime", "CreatedBy", "ModifiedTime", "ModifiedBy")  VALUES ('39F3C49C-ED14-45E0-718C-7D650D850143', 'Admin', 1, '39F3C49C-400A-B33D-0C8F-E878AAABA954', '菜单管理', 'admin_menu', '', '', '', 'menu', '', 1, 1, 0, 0, '', '', 1, '', '2020-03-07 08:40:54', '39F08CFD-8E0D-771B-A2F3-2639A62CA2FA', '2020-06-06 19:20:29', '39F08CFD-8E0D-771B-A2F3-2639A62CA2FA');
INSERT INTO "Menu"("Id", "ModuleCode", "Type", "ParentId", "Name", "RouteName", "RouteParams", "RouteQuery", "Url", "Icon", "IconColor", "Level", "Show", "Sort", "Target", "DialogWidth", "DialogHeight", "DialogFullscreen", "Remarks", "CreatedTime", "CreatedBy", "ModifiedTime", "ModifiedBy")  VALUES ('39F3C49C-FFC8-9DE6-77EB-0FE0A8364F8C', 'Admin', 1, '39F3C49C-400A-B33D-0C8F-E878AAABA954', '角色管理', 'admin_role', '', '', '', 'role', '', 1, 1, 0, 0, '', '', 1, '', '2020-03-07 08:40:59', '39F08CFD-8E0D-771B-A2F3-2639A62CA2FA', '2020-06-06 19:20:29', '39F08CFD-8E0D-771B-A2F3-2639A62CA2FA');
INSERT INTO "Menu"("Id", "ModuleCode", "Type", "ParentId", "Name", "RouteName", "RouteParams", "RouteQuery", "Url", "Icon", "IconColor", "Level", "Show", "Sort", "Target", "DialogWidth", "DialogHeight", "DialogFullscreen", "Remarks", "CreatedTime", "CreatedBy", "ModifiedTime", "ModifiedBy")  VALUES ('39F3C49D-0EB2-662F-2A0D-706F41140D12', 'Admin', 1, '39F3C49C-400A-B33D-0C8F-E878AAABA954', '账户管理', 'admin_account', '', '', '', 'user', '', 1, 1, 0, 0, '', '', 1, '', '2020-03-07 08:41:03', '39F08CFD-8E0D-771B-A2F3-2639A62CA2FA', '2020-06-06 19:20:29', '39F08CFD-8E0D-771B-A2F3-2639A62CA2FA');
INSERT INTO "Menu"("Id", "ModuleCode", "Type", "ParentId", "Name", "RouteName", "RouteParams", "RouteQuery", "Url", "Icon", "IconColor", "Level", "Show", "Sort", "Target", "DialogWidth", "DialogHeight", "DialogFullscreen", "Remarks", "CreatedTime", "CreatedBy", "ModifiedTime", "ModifiedBy")  VALUES ('39F4C72F-10A9-FC03-FCBD-B6A8A29A3709', '', 0, '00000000-0000-0000-0000-000000000000', '系统日志', '', '', '', '', 'log', '', 0, 1, 2, -1, '', '', 1, '', '2020-04-26 13:42:33', '39F08CFD-8E0D-771B-A2F3-2639A62CA2FA', '2020-04-29 19:48:52', '39F08CFD-8E0D-771B-A2F3-2639A62CA2FA');
INSERT INTO "Menu"("Id", "ModuleCode", "Type", "ParentId", "Name", "RouteName", "RouteParams", "RouteQuery", "Url", "Icon", "IconColor", "Level", "Show", "Sort", "Target", "DialogWidth", "DialogHeight", "DialogFullscreen", "Remarks", "CreatedTime", "CreatedBy", "ModifiedTime", "ModifiedBy")  VALUES ('39F4C72F-5F6B-1879-7D4C-7915512406E9', 'Admin', 1, '39F4C72F-10A9-FC03-FCBD-B6A8A29A3709', '审计日志', 'admin_auditinfo', '', '', '', 'log', '', 1, 1, 0, 0, '', '', 1, '', '2020-04-26 13:42:54', '39F08CFD-8E0D-771B-A2F3-2639A62CA2FA', '2020-04-26 13:42:54', '39F08CFD-8E0D-771B-A2F3-2639A62CA2FA');
INSERT INTO "Menu"("Id", "ModuleCode", "Type", "ParentId", "Name", "RouteName", "RouteParams", "RouteQuery", "Url", "Icon", "IconColor", "Level", "Show", "Sort", "Target", "DialogWidth", "DialogHeight", "DialogFullscreen", "Remarks", "CreatedTime", "CreatedBy", "ModifiedTime", "ModifiedBy")  VALUES ('39F4C72F-6E11-71DE-E74B-67B7E152B442', 'Admin', 1, '39F4C72F-10A9-FC03-FCBD-B6A8A29A3709', '登录日志', 'admin_log_login', '', '', '', 'log', '', 1, 1, 0, 0, '', '', 1, '', '2020-04-26 13:42:57', '39F08CFD-8E0D-771B-A2F3-2639A62CA2FA', '2020-04-26 13:52:31', '39F08CFD-8E0D-771B-A2F3-2639A62CA2FA');
INSERT INTO "Menu"("Id", "ModuleCode", "Type", "ParentId", "Name", "RouteName", "RouteParams", "RouteQuery", "Url", "Icon", "IconColor", "Level", "Show", "Sort", "Target", "DialogWidth", "DialogHeight", "DialogFullscreen", "Remarks", "CreatedTime", "CreatedBy", "ModifiedTime", "ModifiedBy")  VALUES ('39F4D6B4-CB9E-0BA7-E46E-442013F4D8BA', 'Admin', 1, '39F3C49C-1756-9047-34B5-6DCFADEFE28D', 'MIME', 'admin_mime', '', '', '', 'media', '', 1, 1, 4, 0, '', '', 1, '', '2020-04-29 14:02:56', '39F08CFD-8E0D-771B-A2F3-2639A62CA2FA', '2020-04-29 21:00:41', '39F08CFD-8E0D-771B-A2F3-2639A62CA2FA');
INSERT INTO "Menu"("Id", "ModuleCode", "Type", "ParentId", "Name", "RouteName", "RouteParams", "RouteQuery", "Url", "Icon", "IconColor", "Level", "Show", "Sort", "Target", "DialogWidth", "DialogHeight", "DialogFullscreen", "Remarks", "CreatedTime", "CreatedBy", "ModifiedTime", "ModifiedBy")  VALUES ('39F4D6D2-3508-0CFC-205E-7BD7B887F3F4', 'Admin', 1, '39F3C49C-1756-9047-34B5-6DCFADEFE28D', '文件管理', 'admin_file', '', '', '', 'attachment', '', 1, 1, 1, 0, '', '', 1, '', '2020-04-29 14:35:03', '39F08CFD-8E0D-771B-A2F3-2639A62CA2FA', '2020-04-29 20:20:20', '39F08CFD-8E0D-771B-A2F3-2639A62CA2FA');
INSERT INTO "Mime"("Ext", "Value") VALUES ('323', 'text/h323');
INSERT INTO "Mime"("Ext", "Value") VALUES ('3g2', 'video/3gpp2');
INSERT INTO "Mime"("Ext", "Value") VALUES ('3gp', 'video/3gpp');
INSERT INTO "Mime"("Ext", "Value") VALUES ('3gp2', 'video/3gpp2');
INSERT INTO "Mime"("Ext", "Value") VALUES ('3gpp', 'video/3gpp');
INSERT INTO "Mime"("Ext", "Value") VALUES ('7z', 'application/x-7z-compressed');
INSERT INTO "Mime"("Ext", "Value") VALUES ('aa', 'audio/audible');
INSERT INTO "Mime"("Ext", "Value") VALUES ('AAC', 'audio/aac');
INSERT INTO "Mime"("Ext", "Value") VALUES ('aaf', 'application/octet-stream');
INSERT INTO "Mime"("Ext", "Value") VALUES ('aax', 'audio/vnd.audible.aax');
INSERT INTO "Mime"("Ext", "Value") VALUES ('ac3', 'audio/ac3');
INSERT INTO "Mime"("Ext", "Value") VALUES ('aca', 'application/octet-stream');
INSERT INTO "Mime"("Ext", "Value") VALUES ('accda', 'application/msaccess.addin');
INSERT INTO "Mime"("Ext", "Value") VALUES ('accdb', 'application/msaccess');
INSERT INTO "Mime"("Ext", "Value") VALUES ('accdc', 'application/msaccess.cab');
INSERT INTO "Mime"("Ext", "Value") VALUES ('accde', 'application/msaccess');
INSERT INTO "Mime"("Ext", "Value") VALUES ('accdr', 'application/msaccess.runtime');
INSERT INTO "Mime"("Ext", "Value") VALUES ('accdt', 'application/msaccess');
INSERT INTO "Mime"("Ext", "Value") VALUES ('accdw', 'application/msaccess.webapplication');
INSERT INTO "Mime"("Ext", "Value") VALUES ('accft', 'application/msaccess.ftemplate');
INSERT INTO "Mime"("Ext", "Value") VALUES ('acx', 'application/internet-property-stream');
INSERT INTO "Mime"("Ext", "Value") VALUES ('AddIn', 'text/xml');
INSERT INTO "Mime"("Ext", "Value") VALUES ('ade', 'application/msaccess');
INSERT INTO "Mime"("Ext", "Value") VALUES ('adobebridge', 'application/x-bridge-url');
INSERT INTO "Mime"("Ext", "Value") VALUES ('adp', 'application/msaccess');
INSERT INTO "Mime"("Ext", "Value") VALUES ('ADT', 'audio/vnd.dlna.adts');
INSERT INTO "Mime"("Ext", "Value") VALUES ('ADTS', 'audio/aac');
INSERT INTO "Mime"("Ext", "Value") VALUES ('afm', 'application/octet-stream');
INSERT INTO "Mime"("Ext", "Value") VALUES ('ai', 'application/postscript');
INSERT INTO "Mime"("Ext", "Value") VALUES ('aif', 'audio/aiff');
INSERT INTO "Mime"("Ext", "Value") VALUES ('aifc', 'audio/aiff');
INSERT INTO "Mime"("Ext", "Value") VALUES ('aiff', 'audio/aiff');
INSERT INTO "Mime"("Ext", "Value") VALUES ('air', 'application/vnd.adobe.air-application-installer-package+zip');
INSERT INTO "Mime"("Ext", "Value") VALUES ('amc', 'application/mpeg');
INSERT INTO "Mime"("Ext", "Value") VALUES ('anx', 'application/annodex');
INSERT INTO "Mime"("Ext", "Value") VALUES ('apk', 'application/vnd.android.package-archive');
INSERT INTO "Mime"("Ext", "Value") VALUES ('application', 'application/x-ms-application');
INSERT INTO "Mime"("Ext", "Value") VALUES ('art', 'image/x-jg');
INSERT INTO "Mime"("Ext", "Value") VALUES ('asa', 'application/xml');
INSERT INTO "Mime"("Ext", "Value") VALUES ('asax', 'application/xml');
INSERT INTO "Mime"("Ext", "Value") VALUES ('ascx', 'application/xml');
INSERT INTO "Mime"("Ext", "Value") VALUES ('asd', 'application/octet-stream');
INSERT INTO "Mime"("Ext", "Value") VALUES ('asf', 'video/x-ms-asf');
INSERT INTO "Mime"("Ext", "Value") VALUES ('ashx', 'application/xml');
INSERT INTO "Mime"("Ext", "Value") VALUES ('asi', 'application/octet-stream');
INSERT INTO "Mime"("Ext", "Value") VALUES ('asm', 'text/plain');
INSERT INTO "Mime"("Ext", "Value") VALUES ('asmx', 'application/xml');
INSERT INTO "Mime"("Ext", "Value") VALUES ('aspx', 'application/xml');
INSERT INTO "Mime"("Ext", "Value") VALUES ('asr', 'video/x-ms-asf');
INSERT INTO "Mime"("Ext", "Value") VALUES ('asx', 'video/x-ms-asf');
INSERT INTO "Mime"("Ext", "Value") VALUES ('atom', 'application/atom+xml');
INSERT INTO "Mime"("Ext", "Value") VALUES ('au', 'audio/basic');
INSERT INTO "Mime"("Ext", "Value") VALUES ('avi', 'video/x-msvideo');
INSERT INTO "Mime"("Ext", "Value") VALUES ('axa', 'audio/annodex');
INSERT INTO "Mime"("Ext", "Value") VALUES ('axs', 'application/olescript');
INSERT INTO "Mime"("Ext", "Value") VALUES ('axv', 'video/annodex');
INSERT INTO "Mime"("Ext", "Value") VALUES ('bas', 'text/plain');
INSERT INTO "Mime"("Ext", "Value") VALUES ('bcpio', 'application/x-bcpio');
INSERT INTO "Mime"("Ext", "Value") VALUES ('bin', 'application/octet-stream');
INSERT INTO "Mime"("Ext", "Value") VALUES ('bmp', 'image/bmp');
INSERT INTO "Mime"("Ext", "Value") VALUES ('c', 'text/plain');
INSERT INTO "Mime"("Ext", "Value") VALUES ('cab', 'application/octet-stream');
INSERT INTO "Mime"("Ext", "Value") VALUES ('caf', 'audio/x-caf');
INSERT INTO "Mime"("Ext", "Value") VALUES ('calx', 'application/vnd.ms-office.calx');
INSERT INTO "Mime"("Ext", "Value") VALUES ('cat', 'application/vnd.ms-pki.seccat');
INSERT INTO "Mime"("Ext", "Value") VALUES ('cc', 'text/plain');
INSERT INTO "Mime"("Ext", "Value") VALUES ('cd', 'text/plain');
INSERT INTO "Mime"("Ext", "Value") VALUES ('cdda', 'audio/aiff');
INSERT INTO "Mime"("Ext", "Value") VALUES ('cdf', 'application/x-cdf');
INSERT INTO "Mime"("Ext", "Value") VALUES ('cer', 'application/x-x509-ca-cert');
INSERT INTO "Mime"("Ext", "Value") VALUES ('cfg', 'text/plain');
INSERT INTO "Mime"("Ext", "Value") VALUES ('chm', 'application/octet-stream');
INSERT INTO "Mime"("Ext", "Value") VALUES ('class', 'application/x-java-applet');
INSERT INTO "Mime"("Ext", "Value") VALUES ('clp', 'application/x-msclip');
INSERT INTO "Mime"("Ext", "Value") VALUES ('cmd', 'text/plain');
INSERT INTO "Mime"("Ext", "Value") VALUES ('cmx', 'image/x-cmx');
INSERT INTO "Mime"("Ext", "Value") VALUES ('cnf', 'text/plain');
INSERT INTO "Mime"("Ext", "Value") VALUES ('cod', 'image/cis-cod');
INSERT INTO "Mime"("Ext", "Value") VALUES ('config', 'application/xml');
INSERT INTO "Mime"("Ext", "Value") VALUES ('contact', 'text/x-ms-contact');
INSERT INTO "Mime"("Ext", "Value") VALUES ('coverage', 'application/xml');
INSERT INTO "Mime"("Ext", "Value") VALUES ('cpio', 'application/x-cpio');
INSERT INTO "Mime"("Ext", "Value") VALUES ('cpp', 'text/plain');
INSERT INTO "Mime"("Ext", "Value") VALUES ('crd', 'application/x-mscardfile');
INSERT INTO "Mime"("Ext", "Value") VALUES ('crl', 'application/pkix-crl');
INSERT INTO "Mime"("Ext", "Value") VALUES ('crt', 'application/x-x509-ca-cert');
INSERT INTO "Mime"("Ext", "Value") VALUES ('cs', 'text/plain');
INSERT INTO "Mime"("Ext", "Value") VALUES ('csdproj', 'text/plain');
INSERT INTO "Mime"("Ext", "Value") VALUES ('csh', 'application/x-csh');
INSERT INTO "Mime"("Ext", "Value") VALUES ('csproj', 'text/plain');
INSERT INTO "Mime"("Ext", "Value") VALUES ('css', 'text/css');
INSERT INTO "Mime"("Ext", "Value") VALUES ('csv', 'text/csv');
INSERT INTO "Mime"("Ext", "Value") VALUES ('cur', 'application/octet-stream');
INSERT INTO "Mime"("Ext", "Value") VALUES ('cxx', 'text/plain');
INSERT INTO "Mime"("Ext", "Value") VALUES ('dat', 'application/octet-stream');
INSERT INTO "Mime"("Ext", "Value") VALUES ('datasource', 'application/xml');
INSERT INTO "Mime"("Ext", "Value") VALUES ('dbproj', 'text/plain');
INSERT INTO "Mime"("Ext", "Value") VALUES ('dcr', 'application/x-director');
INSERT INTO "Mime"("Ext", "Value") VALUES ('def', 'text/plain');
INSERT INTO "Mime"("Ext", "Value") VALUES ('deploy', 'application/octet-stream');
INSERT INTO "Mime"("Ext", "Value") VALUES ('der', 'application/x-x509-ca-cert');
INSERT INTO "Mime"("Ext", "Value") VALUES ('dgml', 'application/xml');
INSERT INTO "Mime"("Ext", "Value") VALUES ('dib', 'image/bmp');
INSERT INTO "Mime"("Ext", "Value") VALUES ('dif', 'video/x-dv');
INSERT INTO "Mime"("Ext", "Value") VALUES ('dir', 'application/x-director');
INSERT INTO "Mime"("Ext", "Value") VALUES ('disco', 'text/xml');
INSERT INTO "Mime"("Ext", "Value") VALUES ('divx', 'video/divx');
INSERT INTO "Mime"("Ext", "Value") VALUES ('dll', 'application/x-msdownload');
INSERT INTO "Mime"("Ext", "Value") VALUES ('dll.config', 'text/xml');
INSERT INTO "Mime"("Ext", "Value") VALUES ('dlm', 'text/dlm');
INSERT INTO "Mime"("Ext", "Value") VALUES ('doc', 'application/msword');
INSERT INTO "Mime"("Ext", "Value") VALUES ('docm', 'application/vnd.ms-word.document.macroEnabled.12');
INSERT INTO "Mime"("Ext", "Value") VALUES ('docx', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document');
INSERT INTO "Mime"("Ext", "Value") VALUES ('dot', 'application/msword');
INSERT INTO "Mime"("Ext", "Value") VALUES ('dotm', 'application/vnd.ms-word.template.macroEnabled.12');
INSERT INTO "Mime"("Ext", "Value") VALUES ('dotx', 'application/vnd.openxmlformats-officedocument.wordprocessingml.template');
INSERT INTO "Mime"("Ext", "Value") VALUES ('dsp', 'application/octet-stream');
INSERT INTO "Mime"("Ext", "Value") VALUES ('dsw', 'text/plain');
INSERT INTO "Mime"("Ext", "Value") VALUES ('dtd', 'text/xml');
INSERT INTO "Mime"("Ext", "Value") VALUES ('dtsConfig', 'text/xml');
INSERT INTO "Mime"("Ext", "Value") VALUES ('dv', 'video/x-dv');
INSERT INTO "Mime"("Ext", "Value") VALUES ('dvi', 'application/x-dvi');
INSERT INTO "Mime"("Ext", "Value") VALUES ('dwf', 'drawing/x-dwf');
INSERT INTO "Mime"("Ext", "Value") VALUES ('dwg', 'application/acad');
INSERT INTO "Mime"("Ext", "Value") VALUES ('dwp', 'application/octet-stream');
INSERT INTO "Mime"("Ext", "Value") VALUES ('dxf', 'application/x-dxf');
INSERT INTO "Mime"("Ext", "Value") VALUES ('dxr', 'application/x-director');
INSERT INTO "Mime"("Ext", "Value") VALUES ('eml', 'message/rfc822');
INSERT INTO "Mime"("Ext", "Value") VALUES ('emz', 'application/octet-stream');
INSERT INTO "Mime"("Ext", "Value") VALUES ('eot', 'application/vnd.ms-fontobject');
INSERT INTO "Mime"("Ext", "Value") VALUES ('eps', 'application/postscript');
INSERT INTO "Mime"("Ext", "Value") VALUES ('es', 'application/ecmascript');
INSERT INTO "Mime"("Ext", "Value") VALUES ('etl', 'application/etl');
INSERT INTO "Mime"("Ext", "Value") VALUES ('etx', 'text/x-setext');
INSERT INTO "Mime"("Ext", "Value") VALUES ('evy', 'application/envoy');
INSERT INTO "Mime"("Ext", "Value") VALUES ('exe', 'application/octet-stream');
INSERT INTO "Mime"("Ext", "Value") VALUES ('exe.config', 'text/xml');
INSERT INTO "Mime"("Ext", "Value") VALUES ('fdf', 'application/vnd.fdf');
INSERT INTO "Mime"("Ext", "Value") VALUES ('fif', 'application/fractals');
INSERT INTO "Mime"("Ext", "Value") VALUES ('filters', 'application/xml');
INSERT INTO "Mime"("Ext", "Value") VALUES ('fla', 'application/octet-stream');
INSERT INTO "Mime"("Ext", "Value") VALUES ('flac', 'audio/flac');
INSERT INTO "Mime"("Ext", "Value") VALUES ('flr', 'x-world/x-vrml');
INSERT INTO "Mime"("Ext", "Value") VALUES ('flv', 'video/x-flv');
INSERT INTO "Mime"("Ext", "Value") VALUES ('fsscript', 'application/fsharp-script');
INSERT INTO "Mime"("Ext", "Value") VALUES ('fsx', 'application/fsharp-script');
INSERT INTO "Mime"("Ext", "Value") VALUES ('generictest', 'application/xml');
INSERT INTO "Mime"("Ext", "Value") VALUES ('gif', 'image/gif');
INSERT INTO "Mime"("Ext", "Value") VALUES ('gpx', 'application/gpx+xml');
INSERT INTO "Mime"("Ext", "Value") VALUES ('group', 'text/x-ms-group');
INSERT INTO "Mime"("Ext", "Value") VALUES ('gsm', 'audio/x-gsm');
INSERT INTO "Mime"("Ext", "Value") VALUES ('gtar', 'application/x-gtar');
INSERT INTO "Mime"("Ext", "Value") VALUES ('gz', 'application/x-gzip');
INSERT INTO "Mime"("Ext", "Value") VALUES ('h', 'text/plain');
INSERT INTO "Mime"("Ext", "Value") VALUES ('hdf', 'application/x-hdf');
INSERT INTO "Mime"("Ext", "Value") VALUES ('hdml', 'text/x-hdml');
INSERT INTO "Mime"("Ext", "Value") VALUES ('hhc', 'application/x-oleobject');
INSERT INTO "Mime"("Ext", "Value") VALUES ('hhk', 'application/octet-stream');
INSERT INTO "Mime"("Ext", "Value") VALUES ('hhp', 'application/octet-stream');
INSERT INTO "Mime"("Ext", "Value") VALUES ('hlp', 'application/winhlp');
INSERT INTO "Mime"("Ext", "Value") VALUES ('hpp', 'text/plain');
INSERT INTO "Mime"("Ext", "Value") VALUES ('hqx', 'application/mac-binhex40');
INSERT INTO "Mime"("Ext", "Value") VALUES ('hta', 'application/hta');
INSERT INTO "Mime"("Ext", "Value") VALUES ('htc', 'text/x-component');
INSERT INTO "Mime"("Ext", "Value") VALUES ('htm', 'text/html');
INSERT INTO "Mime"("Ext", "Value") VALUES ('html', 'text/html');
INSERT INTO "Mime"("Ext", "Value") VALUES ('htt', 'text/webviewhtml');
INSERT INTO "Mime"("Ext", "Value") VALUES ('hxa', 'application/xml');
INSERT INTO "Mime"("Ext", "Value") VALUES ('hxc', 'application/xml');
INSERT INTO "Mime"("Ext", "Value") VALUES ('hxd', 'application/octet-stream');
INSERT INTO "Mime"("Ext", "Value") VALUES ('hxe', 'application/xml');
INSERT INTO "Mime"("Ext", "Value") VALUES ('hxf', 'application/xml');
INSERT INTO "Mime"("Ext", "Value") VALUES ('hxh', 'application/octet-stream');
INSERT INTO "Mime"("Ext", "Value") VALUES ('hxi', 'application/octet-stream');
INSERT INTO "Mime"("Ext", "Value") VALUES ('hxk', 'application/xml');
INSERT INTO "Mime"("Ext", "Value") VALUES ('hxq', 'application/octet-stream');
INSERT INTO "Mime"("Ext", "Value") VALUES ('hxr', 'application/octet-stream');
INSERT INTO "Mime"("Ext", "Value") VALUES ('hxs', 'application/octet-stream');
INSERT INTO "Mime"("Ext", "Value") VALUES ('hxt', 'text/html');
INSERT INTO "Mime"("Ext", "Value") VALUES ('hxv', 'application/xml');
INSERT INTO "Mime"("Ext", "Value") VALUES ('hxw', 'application/octet-stream');
INSERT INTO "Mime"("Ext", "Value") VALUES ('hxx', 'text/plain');
INSERT INTO "Mime"("Ext", "Value") VALUES ('i', 'text/plain');
INSERT INTO "Mime"("Ext", "Value") VALUES ('ico', 'image/x-icon');
INSERT INTO "Mime"("Ext", "Value") VALUES ('ics', 'application/octet-stream');
INSERT INTO "Mime"("Ext", "Value") VALUES ('idl', 'text/plain');
INSERT INTO "Mime"("Ext", "Value") VALUES ('ief', 'image/ief');
INSERT INTO "Mime"("Ext", "Value") VALUES ('iii', 'application/x-iphone');
INSERT INTO "Mime"("Ext", "Value") VALUES ('inc', 'text/plain');
INSERT INTO "Mime"("Ext", "Value") VALUES ('inf', 'application/octet-stream');
INSERT INTO "Mime"("Ext", "Value") VALUES ('ini', 'text/plain');
INSERT INTO "Mime"("Ext", "Value") VALUES ('inl', 'text/plain');
INSERT INTO "Mime"("Ext", "Value") VALUES ('ins', 'application/x-internet-signup');
INSERT INTO "Mime"("Ext", "Value") VALUES ('ipa', 'application/x-itunes-ipa');
INSERT INTO "Mime"("Ext", "Value") VALUES ('ipg', 'application/x-itunes-ipg');
INSERT INTO "Mime"("Ext", "Value") VALUES ('ipproj', 'text/plain');
INSERT INTO "Mime"("Ext", "Value") VALUES ('ipsw', 'application/x-itunes-ipsw');
INSERT INTO "Mime"("Ext", "Value") VALUES ('iqy', 'text/x-ms-iqy');
INSERT INTO "Mime"("Ext", "Value") VALUES ('isp', 'application/x-internet-signup');
INSERT INTO "Mime"("Ext", "Value") VALUES ('ite', 'application/x-itunes-ite');
INSERT INTO "Mime"("Ext", "Value") VALUES ('itlp', 'application/x-itunes-itlp');
INSERT INTO "Mime"("Ext", "Value") VALUES ('itms', 'application/x-itunes-itms');
INSERT INTO "Mime"("Ext", "Value") VALUES ('itpc', 'application/x-itunes-itpc');
INSERT INTO "Mime"("Ext", "Value") VALUES ('IVF', 'video/x-ivf');
INSERT INTO "Mime"("Ext", "Value") VALUES ('jar', 'application/java-archive');
INSERT INTO "Mime"("Ext", "Value") VALUES ('java', 'application/octet-stream');
INSERT INTO "Mime"("Ext", "Value") VALUES ('jck', 'application/liquidmotion');
INSERT INTO "Mime"("Ext", "Value") VALUES ('jcz', 'application/liquidmotion');
INSERT INTO "Mime"("Ext", "Value") VALUES ('jfif', 'image/pjpeg');
INSERT INTO "Mime"("Ext", "Value") VALUES ('jnlp', 'application/x-java-jnlp-file');
INSERT INTO "Mime"("Ext", "Value") VALUES ('jpb', 'application/octet-stream');
INSERT INTO "Mime"("Ext", "Value") VALUES ('jpe', 'image/jpeg');
INSERT INTO "Mime"("Ext", "Value") VALUES ('jpeg', 'image/jpeg');
INSERT INTO "Mime"("Ext", "Value") VALUES ('jpg', 'image/jpeg');
INSERT INTO "Mime"("Ext", "Value") VALUES ('js', 'application/javascript');
INSERT INTO "Mime"("Ext", "Value") VALUES ('json', 'application/json');
INSERT INTO "Mime"("Ext", "Value") VALUES ('jsx', 'text/jscript');
INSERT INTO "Mime"("Ext", "Value") VALUES ('jsxbin', 'text/plain');
INSERT INTO "Mime"("Ext", "Value") VALUES ('latex', 'application/x-latex');
INSERT INTO "Mime"("Ext", "Value") VALUES ('library-ms', 'application/windows-library+xml');
INSERT INTO "Mime"("Ext", "Value") VALUES ('lit', 'application/x-ms-reader');
INSERT INTO "Mime"("Ext", "Value") VALUES ('loadtest', 'application/xml');
INSERT INTO "Mime"("Ext", "Value") VALUES ('lpk', 'application/octet-stream');
INSERT INTO "Mime"("Ext", "Value") VALUES ('lsf', 'video/x-la-asf');
INSERT INTO "Mime"("Ext", "Value") VALUES ('lst', 'text/plain');
INSERT INTO "Mime"("Ext", "Value") VALUES ('lsx', 'video/x-la-asf');
INSERT INTO "Mime"("Ext", "Value") VALUES ('lzh', 'application/octet-stream');
INSERT INTO "Mime"("Ext", "Value") VALUES ('m13', 'application/x-msmediaview');
INSERT INTO "Mime"("Ext", "Value") VALUES ('m14', 'application/x-msmediaview');
INSERT INTO "Mime"("Ext", "Value") VALUES ('m1v', 'video/mpeg');
INSERT INTO "Mime"("Ext", "Value") VALUES ('m2t', 'video/vnd.dlna.mpeg-tts');
INSERT INTO "Mime"("Ext", "Value") VALUES ('m2ts', 'video/vnd.dlna.mpeg-tts');
INSERT INTO "Mime"("Ext", "Value") VALUES ('m2v', 'video/mpeg');
INSERT INTO "Mime"("Ext", "Value") VALUES ('m3u', 'audio/x-mpegurl');
INSERT INTO "Mime"("Ext", "Value") VALUES ('m3u8', 'audio/x-mpegurl');
INSERT INTO "Mime"("Ext", "Value") VALUES ('m4a', 'audio/m4a');
INSERT INTO "Mime"("Ext", "Value") VALUES ('m4b', 'audio/m4b');
INSERT INTO "Mime"("Ext", "Value") VALUES ('m4p', 'audio/m4p');
INSERT INTO "Mime"("Ext", "Value") VALUES ('m4r', 'audio/x-m4r');
INSERT INTO "Mime"("Ext", "Value") VALUES ('m4v', 'video/x-m4v');
INSERT INTO "Mime"("Ext", "Value") VALUES ('mac', 'image/x-macpaint');
INSERT INTO "Mime"("Ext", "Value") VALUES ('mak', 'text/plain');
INSERT INTO "Mime"("Ext", "Value") VALUES ('man', 'application/x-troff-man');
INSERT INTO "Mime"("Ext", "Value") VALUES ('manifest', 'application/x-ms-manifest');
INSERT INTO "Mime"("Ext", "Value") VALUES ('map', 'text/plain');
INSERT INTO "Mime"("Ext", "Value") VALUES ('master', 'application/xml');
INSERT INTO "Mime"("Ext", "Value") VALUES ('mbox', 'application/mbox');
INSERT INTO "Mime"("Ext", "Value") VALUES ('mda', 'application/msaccess');
INSERT INTO "Mime"("Ext", "Value") VALUES ('mdb', 'application/x-msaccess');
INSERT INTO "Mime"("Ext", "Value") VALUES ('mde', 'application/msaccess');
INSERT INTO "Mime"("Ext", "Value") VALUES ('mdp', 'application/octet-stream');
INSERT INTO "Mime"("Ext", "Value") VALUES ('me', 'application/x-troff-me');
INSERT INTO "Mime"("Ext", "Value") VALUES ('mfp', 'application/x-shockwave-flash');
INSERT INTO "Mime"("Ext", "Value") VALUES ('mht', 'message/rfc822');
INSERT INTO "Mime"("Ext", "Value") VALUES ('mhtml', 'message/rfc822');
INSERT INTO "Mime"("Ext", "Value") VALUES ('mid', 'audio/mid');
INSERT INTO "Mime"("Ext", "Value") VALUES ('midi', 'audio/mid');
INSERT INTO "Mime"("Ext", "Value") VALUES ('mix', 'application/octet-stream');
INSERT INTO "Mime"("Ext", "Value") VALUES ('mk', 'text/plain');
INSERT INTO "Mime"("Ext", "Value") VALUES ('mk3d', 'video/x-matroska-3d');
INSERT INTO "Mime"("Ext", "Value") VALUES ('mka', 'audio/x-matroska');
INSERT INTO "Mime"("Ext", "Value") VALUES ('mkv', 'video/x-matroska');
INSERT INTO "Mime"("Ext", "Value") VALUES ('mmf', 'application/x-smaf');
INSERT INTO "Mime"("Ext", "Value") VALUES ('mno', 'text/xml');
INSERT INTO "Mime"("Ext", "Value") VALUES ('mny', 'application/x-msmoney');
INSERT INTO "Mime"("Ext", "Value") VALUES ('mod', 'video/mpeg');
INSERT INTO "Mime"("Ext", "Value") VALUES ('mov', 'video/quicktime');
INSERT INTO "Mime"("Ext", "Value") VALUES ('movie', 'video/x-sgi-movie');
INSERT INTO "Mime"("Ext", "Value") VALUES ('mp2', 'video/mpeg');
INSERT INTO "Mime"("Ext", "Value") VALUES ('mp2v', 'video/mpeg');
INSERT INTO "Mime"("Ext", "Value") VALUES ('mp3', 'audio/mpeg');
INSERT INTO "Mime"("Ext", "Value") VALUES ('mp4', 'video/mp4');
INSERT INTO "Mime"("Ext", "Value") VALUES ('mp4v', 'video/mp4');
INSERT INTO "Mime"("Ext", "Value") VALUES ('mpa', 'video/mpeg');
INSERT INTO "Mime"("Ext", "Value") VALUES ('mpe', 'video/mpeg');
INSERT INTO "Mime"("Ext", "Value") VALUES ('mpeg', 'video/mpeg');
INSERT INTO "Mime"("Ext", "Value") VALUES ('mpf', 'application/vnd.ms-mediapackage');
INSERT INTO "Mime"("Ext", "Value") VALUES ('mpg', 'video/mpeg');
INSERT INTO "Mime"("Ext", "Value") VALUES ('mpp', 'application/vnd.ms-project');
INSERT INTO "Mime"("Ext", "Value") VALUES ('mpv2', 'video/mpeg');
INSERT INTO "Mime"("Ext", "Value") VALUES ('mqv', 'video/quicktime');
INSERT INTO "Mime"("Ext", "Value") VALUES ('ms', 'application/x-troff-ms');
INSERT INTO "Mime"("Ext", "Value") VALUES ('msg', 'application/vnd.ms-outlook');
INSERT INTO "Mime"("Ext", "Value") VALUES ('msi', 'application/octet-stream');
INSERT INTO "Mime"("Ext", "Value") VALUES ('mso', 'application/octet-stream');
INSERT INTO "Mime"("Ext", "Value") VALUES ('mts', 'video/vnd.dlna.mpeg-tts');
INSERT INTO "Mime"("Ext", "Value") VALUES ('mtx', 'application/xml');
INSERT INTO "Mime"("Ext", "Value") VALUES ('mvb', 'application/x-msmediaview');
INSERT INTO "Mime"("Ext", "Value") VALUES ('mvc', 'application/x-miva-compiled');
INSERT INTO "Mime"("Ext", "Value") VALUES ('mxp', 'application/x-mmxp');
INSERT INTO "Mime"("Ext", "Value") VALUES ('nc', 'application/x-netcdf');
INSERT INTO "Mime"("Ext", "Value") VALUES ('nsc', 'video/x-ms-asf');
INSERT INTO "Mime"("Ext", "Value") VALUES ('nws', 'message/rfc822');
INSERT INTO "Mime"("Ext", "Value") VALUES ('ocx', 'application/octet-stream');
INSERT INTO "Mime"("Ext", "Value") VALUES ('oda', 'application/oda');
INSERT INTO "Mime"("Ext", "Value") VALUES ('odb', 'application/vnd.oasis.opendocument.database');
INSERT INTO "Mime"("Ext", "Value") VALUES ('odc', 'application/vnd.oasis.opendocument.chart');
INSERT INTO "Mime"("Ext", "Value") VALUES ('odf', 'application/vnd.oasis.opendocument.formula');
INSERT INTO "Mime"("Ext", "Value") VALUES ('odg', 'application/vnd.oasis.opendocument.graphics');
INSERT INTO "Mime"("Ext", "Value") VALUES ('odh', 'text/plain');
INSERT INTO "Mime"("Ext", "Value") VALUES ('odi', 'application/vnd.oasis.opendocument.image');
INSERT INTO "Mime"("Ext", "Value") VALUES ('odl', 'text/plain');
INSERT INTO "Mime"("Ext", "Value") VALUES ('odm', 'application/vnd.oasis.opendocument.text-master');
INSERT INTO "Mime"("Ext", "Value") VALUES ('odp', 'application/vnd.oasis.opendocument.presentation');
INSERT INTO "Mime"("Ext", "Value") VALUES ('ods', 'application/vnd.oasis.opendocument.spreadsheet');
INSERT INTO "Mime"("Ext", "Value") VALUES ('odt', 'application/vnd.oasis.opendocument.text');
INSERT INTO "Mime"("Ext", "Value") VALUES ('oga', 'audio/ogg');
INSERT INTO "Mime"("Ext", "Value") VALUES ('ogg', 'audio/ogg');
INSERT INTO "Mime"("Ext", "Value") VALUES ('ogv', 'video/ogg');
INSERT INTO "Mime"("Ext", "Value") VALUES ('ogx', 'application/ogg');
INSERT INTO "Mime"("Ext", "Value") VALUES ('one', 'application/onenote');
INSERT INTO "Mime"("Ext", "Value") VALUES ('onea', 'application/onenote');
INSERT INTO "Mime"("Ext", "Value") VALUES ('onepkg', 'application/onenote');
INSERT INTO "Mime"("Ext", "Value") VALUES ('onetmp', 'application/onenote');
INSERT INTO "Mime"("Ext", "Value") VALUES ('onetoc', 'application/onenote');
INSERT INTO "Mime"("Ext", "Value") VALUES ('onetoc2', 'application/onenote');
INSERT INTO "Mime"("Ext", "Value") VALUES ('opus', 'audio/ogg');
INSERT INTO "Mime"("Ext", "Value") VALUES ('orderedtest', 'application/xml');
INSERT INTO "Mime"("Ext", "Value") VALUES ('osdx', 'application/opensearchdescription+xml');
INSERT INTO "Mime"("Ext", "Value") VALUES ('otf', 'application/font-sfnt');
INSERT INTO "Mime"("Ext", "Value") VALUES ('otg', 'application/vnd.oasis.opendocument.graphics-template');
INSERT INTO "Mime"("Ext", "Value") VALUES ('oth', 'application/vnd.oasis.opendocument.text-web');
INSERT INTO "Mime"("Ext", "Value") VALUES ('otp', 'application/vnd.oasis.opendocument.presentation-template');
INSERT INTO "Mime"("Ext", "Value") VALUES ('ots', 'application/vnd.oasis.opendocument.spreadsheet-template');
INSERT INTO "Mime"("Ext", "Value") VALUES ('ott', 'application/vnd.oasis.opendocument.text-template');
INSERT INTO "Mime"("Ext", "Value") VALUES ('oxt', 'application/vnd.openofficeorg.extension');
INSERT INTO "Mime"("Ext", "Value") VALUES ('p10', 'application/pkcs10');
INSERT INTO "Mime"("Ext", "Value") VALUES ('p12', 'application/x-pkcs12');
INSERT INTO "Mime"("Ext", "Value") VALUES ('p7b', 'application/x-pkcs7-certificates');
INSERT INTO "Mime"("Ext", "Value") VALUES ('p7c', 'application/pkcs7-mime');
INSERT INTO "Mime"("Ext", "Value") VALUES ('p7m', 'application/pkcs7-mime');
INSERT INTO "Mime"("Ext", "Value") VALUES ('p7r', 'application/x-pkcs7-certreqresp');
INSERT INTO "Mime"("Ext", "Value") VALUES ('p7s', 'application/pkcs7-signature');
INSERT INTO "Mime"("Ext", "Value") VALUES ('pbm', 'image/x-portable-bitmap');
INSERT INTO "Mime"("Ext", "Value") VALUES ('pcast', 'application/x-podcast');
INSERT INTO "Mime"("Ext", "Value") VALUES ('pct', 'image/pict');
INSERT INTO "Mime"("Ext", "Value") VALUES ('pcx', 'application/octet-stream');
INSERT INTO "Mime"("Ext", "Value") VALUES ('pcz', 'application/octet-stream');
INSERT INTO "Mime"("Ext", "Value") VALUES ('pdf', 'application/pdf');
INSERT INTO "Mime"("Ext", "Value") VALUES ('pfb', 'application/octet-stream');
INSERT INTO "Mime"("Ext", "Value") VALUES ('pfm', 'application/octet-stream');
INSERT INTO "Mime"("Ext", "Value") VALUES ('pfx', 'application/x-pkcs12');
INSERT INTO "Mime"("Ext", "Value") VALUES ('pgm', 'image/x-portable-graymap');
INSERT INTO "Mime"("Ext", "Value") VALUES ('pic', 'image/pict');
INSERT INTO "Mime"("Ext", "Value") VALUES ('pict', 'image/pict');
INSERT INTO "Mime"("Ext", "Value") VALUES ('pkgdef', 'text/plain');
INSERT INTO "Mime"("Ext", "Value") VALUES ('pkgundef', 'text/plain');
INSERT INTO "Mime"("Ext", "Value") VALUES ('pko', 'application/vnd.ms-pki.pko');
INSERT INTO "Mime"("Ext", "Value") VALUES ('pls', 'audio/scpls');
INSERT INTO "Mime"("Ext", "Value") VALUES ('pma', 'application/x-perfmon');
INSERT INTO "Mime"("Ext", "Value") VALUES ('pmc', 'application/x-perfmon');
INSERT INTO "Mime"("Ext", "Value") VALUES ('pml', 'application/x-perfmon');
INSERT INTO "Mime"("Ext", "Value") VALUES ('pmr', 'application/x-perfmon');
INSERT INTO "Mime"("Ext", "Value") VALUES ('pmw', 'application/x-perfmon');
INSERT INTO "Mime"("Ext", "Value") VALUES ('png', 'image/png');
INSERT INTO "Mime"("Ext", "Value") VALUES ('pnm', 'image/x-portable-anymap');
INSERT INTO "Mime"("Ext", "Value") VALUES ('pnt', 'image/x-macpaint');
INSERT INTO "Mime"("Ext", "Value") VALUES ('pntg', 'image/x-macpaint');
INSERT INTO "Mime"("Ext", "Value") VALUES ('pnz', 'image/png');
INSERT INTO "Mime"("Ext", "Value") VALUES ('pot', 'application/vnd.ms-powerpoint');
INSERT INTO "Mime"("Ext", "Value") VALUES ('potm', 'application/vnd.ms-powerpoint.template.macroEnabled.12');
INSERT INTO "Mime"("Ext", "Value") VALUES ('potx', 'application/vnd.openxmlformats-officedocument.presentationml.template');
INSERT INTO "Mime"("Ext", "Value") VALUES ('ppa', 'application/vnd.ms-powerpoint');
INSERT INTO "Mime"("Ext", "Value") VALUES ('ppam', 'application/vnd.ms-powerpoint.addin.macroEnabled.12');
INSERT INTO "Mime"("Ext", "Value") VALUES ('ppm', 'image/x-portable-pixmap');
INSERT INTO "Mime"("Ext", "Value") VALUES ('pps', 'application/vnd.ms-powerpoint');
INSERT INTO "Mime"("Ext", "Value") VALUES ('ppsm', 'application/vnd.ms-powerpoint.slideshow.macroEnabled.12');
INSERT INTO "Mime"("Ext", "Value") VALUES ('ppsx', 'application/vnd.openxmlformats-officedocument.presentationml.slideshow');
INSERT INTO "Mime"("Ext", "Value") VALUES ('ppt', 'application/vnd.ms-powerpoint');
INSERT INTO "Mime"("Ext", "Value") VALUES ('pptm', 'application/vnd.ms-powerpoint.presentation.macroEnabled.12');
INSERT INTO "Mime"("Ext", "Value") VALUES ('pptx', 'application/vnd.openxmlformats-officedocument.presentationml.presentation');
INSERT INTO "Mime"("Ext", "Value") VALUES ('prf', 'application/pics-rules');
INSERT INTO "Mime"("Ext", "Value") VALUES ('prm', 'application/octet-stream');
INSERT INTO "Mime"("Ext", "Value") VALUES ('prx', 'application/octet-stream');
INSERT INTO "Mime"("Ext", "Value") VALUES ('ps', 'application/postscript');
INSERT INTO "Mime"("Ext", "Value") VALUES ('psc1', 'application/PowerShell');
INSERT INTO "Mime"("Ext", "Value") VALUES ('psd', 'application/octet-stream');
INSERT INTO "Mime"("Ext", "Value") VALUES ('psess', 'application/xml');
INSERT INTO "Mime"("Ext", "Value") VALUES ('psm', 'application/octet-stream');
INSERT INTO "Mime"("Ext", "Value") VALUES ('psp', 'application/octet-stream');
INSERT INTO "Mime"("Ext", "Value") VALUES ('pst', 'application/vnd.ms-outlook');
INSERT INTO "Mime"("Ext", "Value") VALUES ('pub', 'application/x-mspublisher');
INSERT INTO "Mime"("Ext", "Value") VALUES ('pwz', 'application/vnd.ms-powerpoint');
INSERT INTO "Mime"("Ext", "Value") VALUES ('qht', 'text/x-html-insertion');
INSERT INTO "Mime"("Ext", "Value") VALUES ('qhtm', 'text/x-html-insertion');
INSERT INTO "Mime"("Ext", "Value") VALUES ('qt', 'video/quicktime');
INSERT INTO "Mime"("Ext", "Value") VALUES ('qti', 'image/x-quicktime');
INSERT INTO "Mime"("Ext", "Value") VALUES ('qtif', 'image/x-quicktime');
INSERT INTO "Mime"("Ext", "Value") VALUES ('qtl', 'application/x-quicktimeplayer');
INSERT INTO "Mime"("Ext", "Value") VALUES ('qxd', 'application/octet-stream');
INSERT INTO "Mime"("Ext", "Value") VALUES ('ra', 'audio/x-pn-realaudio');
INSERT INTO "Mime"("Ext", "Value") VALUES ('ram', 'audio/x-pn-realaudio');
INSERT INTO "Mime"("Ext", "Value") VALUES ('rar', 'application/x-rar-compressed');
INSERT INTO "Mime"("Ext", "Value") VALUES ('ras', 'image/x-cmu-raster');
INSERT INTO "Mime"("Ext", "Value") VALUES ('rat', 'application/rat-file');
INSERT INTO "Mime"("Ext", "Value") VALUES ('rc', 'text/plain');
INSERT INTO "Mime"("Ext", "Value") VALUES ('rc2', 'text/plain');
INSERT INTO "Mime"("Ext", "Value") VALUES ('rct', 'text/plain');
INSERT INTO "Mime"("Ext", "Value") VALUES ('rdlc', 'application/xml');
INSERT INTO "Mime"("Ext", "Value") VALUES ('reg', 'text/plain');
INSERT INTO "Mime"("Ext", "Value") VALUES ('resx', 'application/xml');
INSERT INTO "Mime"("Ext", "Value") VALUES ('rf', 'image/vnd.rn-realflash');
INSERT INTO "Mime"("Ext", "Value") VALUES ('rgb', 'image/x-rgb');
INSERT INTO "Mime"("Ext", "Value") VALUES ('rgs', 'text/plain');
INSERT INTO "Mime"("Ext", "Value") VALUES ('rm', 'application/vnd.rn-realmedia');
INSERT INTO "Mime"("Ext", "Value") VALUES ('rmi', 'audio/mid');
INSERT INTO "Mime"("Ext", "Value") VALUES ('rmp', 'application/vnd.rn-rn_music_package');
INSERT INTO "Mime"("Ext", "Value") VALUES ('roff', 'application/x-troff');
INSERT INTO "Mime"("Ext", "Value") VALUES ('rpm', 'audio/x-pn-realaudio-plugin');
INSERT INTO "Mime"("Ext", "Value") VALUES ('rqy', 'text/x-ms-rqy');
INSERT INTO "Mime"("Ext", "Value") VALUES ('rtf', 'application/rtf');
INSERT INTO "Mime"("Ext", "Value") VALUES ('rtx', 'text/richtext');
INSERT INTO "Mime"("Ext", "Value") VALUES ('rvt', 'application/octet-stream');
INSERT INTO "Mime"("Ext", "Value") VALUES ('ruleset', 'application/xml');
INSERT INTO "Mime"("Ext", "Value") VALUES ('s', 'text/plain');
INSERT INTO "Mime"("Ext", "Value") VALUES ('safariextz', 'application/x-safari-safariextz');
INSERT INTO "Mime"("Ext", "Value") VALUES ('scd', 'application/x-msschedule');
INSERT INTO "Mime"("Ext", "Value") VALUES ('scr', 'text/plain');
INSERT INTO "Mime"("Ext", "Value") VALUES ('sct', 'text/scriptlet');
INSERT INTO "Mime"("Ext", "Value") VALUES ('sd2', 'audio/x-sd2');
INSERT INTO "Mime"("Ext", "Value") VALUES ('sdp', 'application/sdp');
INSERT INTO "Mime"("Ext", "Value") VALUES ('sea', 'application/octet-stream');
INSERT INTO "Mime"("Ext", "Value") VALUES ('searchConnector-ms', 'application/windows-search-connector+xml');
INSERT INTO "Mime"("Ext", "Value") VALUES ('setpay', 'application/set-payment-initiation');
INSERT INTO "Mime"("Ext", "Value") VALUES ('setreg', 'application/set-registration-initiation');
INSERT INTO "Mime"("Ext", "Value") VALUES ('settings', 'application/xml');
INSERT INTO "Mime"("Ext", "Value") VALUES ('sgimb', 'application/x-sgimb');
INSERT INTO "Mime"("Ext", "Value") VALUES ('sgml', 'text/sgml');
INSERT INTO "Mime"("Ext", "Value") VALUES ('sh', 'application/x-sh');
INSERT INTO "Mime"("Ext", "Value") VALUES ('shar', 'application/x-shar');
INSERT INTO "Mime"("Ext", "Value") VALUES ('shtml', 'text/html');
INSERT INTO "Mime"("Ext", "Value") VALUES ('sit', 'application/x-stuffit');
INSERT INTO "Mime"("Ext", "Value") VALUES ('sitemap', 'application/xml');
INSERT INTO "Mime"("Ext", "Value") VALUES ('skin', 'application/xml');
INSERT INTO "Mime"("Ext", "Value") VALUES ('skp', 'application/x-koan');
INSERT INTO "Mime"("Ext", "Value") VALUES ('sldm', 'application/vnd.ms-powerpoint.slide.macroEnabled.12');
INSERT INTO "Mime"("Ext", "Value") VALUES ('sldx', 'application/vnd.openxmlformats-officedocument.presentationml.slide');
INSERT INTO "Mime"("Ext", "Value") VALUES ('slk', 'application/vnd.ms-excel');
INSERT INTO "Mime"("Ext", "Value") VALUES ('sln', 'text/plain');
INSERT INTO "Mime"("Ext", "Value") VALUES ('slupkg-ms', 'application/x-ms-license');
INSERT INTO "Mime"("Ext", "Value") VALUES ('smd', 'audio/x-smd');
INSERT INTO "Mime"("Ext", "Value") VALUES ('smi', 'application/octet-stream');
INSERT INTO "Mime"("Ext", "Value") VALUES ('smx', 'audio/x-smd');
INSERT INTO "Mime"("Ext", "Value") VALUES ('smz', 'audio/x-smd');
INSERT INTO "Mime"("Ext", "Value") VALUES ('snd', 'audio/basic');
INSERT INTO "Mime"("Ext", "Value") VALUES ('snippet', 'application/xml');
INSERT INTO "Mime"("Ext", "Value") VALUES ('snp', 'application/octet-stream');
INSERT INTO "Mime"("Ext", "Value") VALUES ('sol', 'text/plain');
INSERT INTO "Mime"("Ext", "Value") VALUES ('sor', 'text/plain');
INSERT INTO "Mime"("Ext", "Value") VALUES ('spc', 'application/x-pkcs7-certificates');
INSERT INTO "Mime"("Ext", "Value") VALUES ('spl', 'application/futuresplash');
INSERT INTO "Mime"("Ext", "Value") VALUES ('spx', 'audio/ogg');
INSERT INTO "Mime"("Ext", "Value") VALUES ('src', 'application/x-wais-source');
INSERT INTO "Mime"("Ext", "Value") VALUES ('srf', 'text/plain');
INSERT INTO "Mime"("Ext", "Value") VALUES ('SSISDeploymentManifest', 'text/xml');
INSERT INTO "Mime"("Ext", "Value") VALUES ('ssm', 'application/streamingmedia');
INSERT INTO "Mime"("Ext", "Value") VALUES ('sst', 'application/vnd.ms-pki.certstore');
INSERT INTO "Mime"("Ext", "Value") VALUES ('stl', 'application/vnd.ms-pki.stl');
INSERT INTO "Mime"("Ext", "Value") VALUES ('sv4cpio', 'application/x-sv4cpio');
INSERT INTO "Mime"("Ext", "Value") VALUES ('sv4crc', 'application/x-sv4crc');
INSERT INTO "Mime"("Ext", "Value") VALUES ('svc', 'application/xml');
INSERT INTO "Mime"("Ext", "Value") VALUES ('svg', 'image/svg+xml');
INSERT INTO "Mime"("Ext", "Value") VALUES ('swf', 'application/x-shockwave-flash');
INSERT INTO "Mime"("Ext", "Value") VALUES ('step', 'application/step');
INSERT INTO "Mime"("Ext", "Value") VALUES ('stp', 'application/step');
INSERT INTO "Mime"("Ext", "Value") VALUES ('t', 'application/x-troff');
INSERT INTO "Mime"("Ext", "Value") VALUES ('tar', 'application/x-tar');
INSERT INTO "Mime"("Ext", "Value") VALUES ('tcl', 'application/x-tcl');
INSERT INTO "Mime"("Ext", "Value") VALUES ('testrunconfig', 'application/xml');
INSERT INTO "Mime"("Ext", "Value") VALUES ('testsettings', 'application/xml');
INSERT INTO "Mime"("Ext", "Value") VALUES ('tex', 'application/x-tex');
INSERT INTO "Mime"("Ext", "Value") VALUES ('texi', 'application/x-texinfo');
INSERT INTO "Mime"("Ext", "Value") VALUES ('texinfo', 'application/x-texinfo');
INSERT INTO "Mime"("Ext", "Value") VALUES ('tgz', 'application/x-compressed');
INSERT INTO "Mime"("Ext", "Value") VALUES ('thmx', 'application/vnd.ms-officetheme');
INSERT INTO "Mime"("Ext", "Value") VALUES ('thn', 'application/octet-stream');
INSERT INTO "Mime"("Ext", "Value") VALUES ('tif', 'image/tiff');
INSERT INTO "Mime"("Ext", "Value") VALUES ('tiff', 'image/tiff');
INSERT INTO "Mime"("Ext", "Value") VALUES ('tlh', 'text/plain');
INSERT INTO "Mime"("Ext", "Value") VALUES ('tli', 'text/plain');
INSERT INTO "Mime"("Ext", "Value") VALUES ('toc', 'application/octet-stream');
INSERT INTO "Mime"("Ext", "Value") VALUES ('tr', 'application/x-troff');
INSERT INTO "Mime"("Ext", "Value") VALUES ('trm', 'application/x-msterminal');
INSERT INTO "Mime"("Ext", "Value") VALUES ('trx', 'application/xml');
INSERT INTO "Mime"("Ext", "Value") VALUES ('ts', 'video/vnd.dlna.mpeg-tts');
INSERT INTO "Mime"("Ext", "Value") VALUES ('tsv', 'text/tab-separated-values');
INSERT INTO "Mime"("Ext", "Value") VALUES ('ttf', 'application/font-sfnt');
INSERT INTO "Mime"("Ext", "Value") VALUES ('tts', 'video/vnd.dlna.mpeg-tts');
INSERT INTO "Mime"("Ext", "Value") VALUES ('txt', 'text/plain');
INSERT INTO "Mime"("Ext", "Value") VALUES ('u32', 'application/octet-stream');
INSERT INTO "Mime"("Ext", "Value") VALUES ('uls', 'text/iuls');
INSERT INTO "Mime"("Ext", "Value") VALUES ('user', 'text/plain');
INSERT INTO "Mime"("Ext", "Value") VALUES ('ustar', 'application/x-ustar');
INSERT INTO "Mime"("Ext", "Value") VALUES ('vb', 'text/plain');
INSERT INTO "Mime"("Ext", "Value") VALUES ('vbdproj', 'text/plain');
INSERT INTO "Mime"("Ext", "Value") VALUES ('vbk', 'video/mpeg');
INSERT INTO "Mime"("Ext", "Value") VALUES ('vbproj', 'text/plain');
INSERT INTO "Mime"("Ext", "Value") VALUES ('vbs', 'text/vbscript');
INSERT INTO "Mime"("Ext", "Value") VALUES ('vcf', 'text/x-vcard');
INSERT INTO "Mime"("Ext", "Value") VALUES ('vcproj', 'application/xml');
INSERT INTO "Mime"("Ext", "Value") VALUES ('vcs', 'text/plain');
INSERT INTO "Mime"("Ext", "Value") VALUES ('vcxproj', 'application/xml');
INSERT INTO "Mime"("Ext", "Value") VALUES ('vddproj', 'text/plain');
INSERT INTO "Mime"("Ext", "Value") VALUES ('vdp', 'text/plain');
INSERT INTO "Mime"("Ext", "Value") VALUES ('vdproj', 'text/plain');
INSERT INTO "Mime"("Ext", "Value") VALUES ('vdx', 'application/vnd.ms-visio.viewer');
INSERT INTO "Mime"("Ext", "Value") VALUES ('vml', 'text/xml');
INSERT INTO "Mime"("Ext", "Value") VALUES ('vscontent', 'application/xml');
INSERT INTO "Mime"("Ext", "Value") VALUES ('vsct', 'text/xml');
INSERT INTO "Mime"("Ext", "Value") VALUES ('vsd', 'application/vnd.visio');
INSERT INTO "Mime"("Ext", "Value") VALUES ('vsi', 'application/ms-vsi');
INSERT INTO "Mime"("Ext", "Value") VALUES ('vsix', 'application/vsix');
INSERT INTO "Mime"("Ext", "Value") VALUES ('vsixlangpack', 'text/xml');
INSERT INTO "Mime"("Ext", "Value") VALUES ('vsixmanifest', 'text/xml');
INSERT INTO "Mime"("Ext", "Value") VALUES ('vsmdi', 'application/xml');
INSERT INTO "Mime"("Ext", "Value") VALUES ('vspscc', 'text/plain');
INSERT INTO "Mime"("Ext", "Value") VALUES ('vss', 'application/vnd.visio');
INSERT INTO "Mime"("Ext", "Value") VALUES ('vsscc', 'text/plain');
INSERT INTO "Mime"("Ext", "Value") VALUES ('vssettings', 'text/xml');
INSERT INTO "Mime"("Ext", "Value") VALUES ('vssscc', 'text/plain');
INSERT INTO "Mime"("Ext", "Value") VALUES ('vst', 'application/vnd.visio');
INSERT INTO "Mime"("Ext", "Value") VALUES ('vstemplate', 'text/xml');
INSERT INTO "Mime"("Ext", "Value") VALUES ('vsto', 'application/x-ms-vsto');
INSERT INTO "Mime"("Ext", "Value") VALUES ('vsw', 'application/vnd.visio');
INSERT INTO "Mime"("Ext", "Value") VALUES ('vsx', 'application/vnd.visio');
INSERT INTO "Mime"("Ext", "Value") VALUES ('vtt', 'text/vtt');
INSERT INTO "Mime"("Ext", "Value") VALUES ('vtx', 'application/vnd.visio');
INSERT INTO "Mime"("Ext", "Value") VALUES ('wasm', 'application/wasm');
INSERT INTO "Mime"("Ext", "Value") VALUES ('wav', 'audio/wav');
INSERT INTO "Mime"("Ext", "Value") VALUES ('wave', 'audio/wav');
INSERT INTO "Mime"("Ext", "Value") VALUES ('wax', 'audio/x-ms-wax');
INSERT INTO "Mime"("Ext", "Value") VALUES ('wbk', 'application/msword');
INSERT INTO "Mime"("Ext", "Value") VALUES ('wbmp', 'image/vnd.wap.wbmp');
INSERT INTO "Mime"("Ext", "Value") VALUES ('wcm', 'application/vnd.ms-works');
INSERT INTO "Mime"("Ext", "Value") VALUES ('wdb', 'application/vnd.ms-works');
INSERT INTO "Mime"("Ext", "Value") VALUES ('wdp', 'image/vnd.ms-photo');
INSERT INTO "Mime"("Ext", "Value") VALUES ('webarchive', 'application/x-safari-webarchive');
INSERT INTO "Mime"("Ext", "Value") VALUES ('webm', 'video/webm');
INSERT INTO "Mime"("Ext", "Value") VALUES ('webp', 'image/webp');
INSERT INTO "Mime"("Ext", "Value") VALUES ('webtest', 'application/xml');
INSERT INTO "Mime"("Ext", "Value") VALUES ('wiq', 'application/xml');
INSERT INTO "Mime"("Ext", "Value") VALUES ('wiz', 'application/msword');
INSERT INTO "Mime"("Ext", "Value") VALUES ('wks', 'application/vnd.ms-works');
INSERT INTO "Mime"("Ext", "Value") VALUES ('WLMP', 'application/wlmoviemaker');
INSERT INTO "Mime"("Ext", "Value") VALUES ('wlpginstall', 'application/x-wlpg-detect');
INSERT INTO "Mime"("Ext", "Value") VALUES ('wlpginstall3', 'application/x-wlpg3-detect');
INSERT INTO "Mime"("Ext", "Value") VALUES ('wm', 'video/x-ms-wm');
INSERT INTO "Mime"("Ext", "Value") VALUES ('wma', 'audio/x-ms-wma');
INSERT INTO "Mime"("Ext", "Value") VALUES ('wmd', 'application/x-ms-wmd');
INSERT INTO "Mime"("Ext", "Value") VALUES ('wmf', 'application/x-msmetafile');
INSERT INTO "Mime"("Ext", "Value") VALUES ('wml', 'text/vnd.wap.wml');
INSERT INTO "Mime"("Ext", "Value") VALUES ('wmlc', 'application/vnd.wap.wmlc');
INSERT INTO "Mime"("Ext", "Value") VALUES ('wmls', 'text/vnd.wap.wmlscript');
INSERT INTO "Mime"("Ext", "Value") VALUES ('wmlsc', 'application/vnd.wap.wmlscriptc');
INSERT INTO "Mime"("Ext", "Value") VALUES ('wmp', 'video/x-ms-wmp');
INSERT INTO "Mime"("Ext", "Value") VALUES ('wmv', 'video/x-ms-wmv');
INSERT INTO "Mime"("Ext", "Value") VALUES ('wmx', 'video/x-ms-wmx');
INSERT INTO "Mime"("Ext", "Value") VALUES ('wmz', 'application/x-ms-wmz');
INSERT INTO "Mime"("Ext", "Value") VALUES ('woff', 'application/font-woff');
INSERT INTO "Mime"("Ext", "Value") VALUES ('woff2', 'application/font-woff2');
INSERT INTO "Mime"("Ext", "Value") VALUES ('wpl', 'application/vnd.ms-wpl');
INSERT INTO "Mime"("Ext", "Value") VALUES ('wps', 'application/vnd.ms-works');
INSERT INTO "Mime"("Ext", "Value") VALUES ('wri', 'application/x-mswrite');
INSERT INTO "Mime"("Ext", "Value") VALUES ('wrl', 'x-world/x-vrml');
INSERT INTO "Mime"("Ext", "Value") VALUES ('wrz', 'x-world/x-vrml');
INSERT INTO "Mime"("Ext", "Value") VALUES ('wsc', 'text/scriptlet');
INSERT INTO "Mime"("Ext", "Value") VALUES ('wsdl', 'text/xml');
INSERT INTO "Mime"("Ext", "Value") VALUES ('wvx', 'video/x-ms-wvx');
INSERT INTO "Mime"("Ext", "Value") VALUES ('x', 'application/directx');
INSERT INTO "Mime"("Ext", "Value") VALUES ('xaf', 'x-world/x-vrml');
INSERT INTO "Mime"("Ext", "Value") VALUES ('xaml', 'application/xaml+xml');
INSERT INTO "Mime"("Ext", "Value") VALUES ('xap', 'application/x-silverlight-app');
INSERT INTO "Mime"("Ext", "Value") VALUES ('xbap', 'application/x-ms-xbap');
INSERT INTO "Mime"("Ext", "Value") VALUES ('xbm', 'image/x-xbitmap');
INSERT INTO "Mime"("Ext", "Value") VALUES ('xdr', 'text/plain');
INSERT INTO "Mime"("Ext", "Value") VALUES ('xht', 'application/xhtml+xml');
INSERT INTO "Mime"("Ext", "Value") VALUES ('xhtml', 'application/xhtml+xml');
INSERT INTO "Mime"("Ext", "Value") VALUES ('xla', 'application/vnd.ms-excel');
INSERT INTO "Mime"("Ext", "Value") VALUES ('xlam', 'application/vnd.ms-excel.addin.macroEnabled.12');
INSERT INTO "Mime"("Ext", "Value") VALUES ('xlc', 'application/vnd.ms-excel');
INSERT INTO "Mime"("Ext", "Value") VALUES ('xld', 'application/vnd.ms-excel');
INSERT INTO "Mime"("Ext", "Value") VALUES ('xlk', 'application/vnd.ms-excel');
INSERT INTO "Mime"("Ext", "Value") VALUES ('xll', 'application/vnd.ms-excel');
INSERT INTO "Mime"("Ext", "Value") VALUES ('xlm', 'application/vnd.ms-excel');
INSERT INTO "Mime"("Ext", "Value") VALUES ('xls', 'application/vnd.ms-excel');
INSERT INTO "Mime"("Ext", "Value") VALUES ('xlsb', 'application/vnd.ms-excel.sheet.binary.macroEnabled.12');
INSERT INTO "Mime"("Ext", "Value") VALUES ('xlsm', 'application/vnd.ms-excel.sheet.macroEnabled.12');
INSERT INTO "Mime"("Ext", "Value") VALUES ('xlsx', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
INSERT INTO "Mime"("Ext", "Value") VALUES ('xlt', 'application/vnd.ms-excel');
INSERT INTO "Mime"("Ext", "Value") VALUES ('xltm', 'application/vnd.ms-excel.template.macroEnabled.12');
INSERT INTO "Mime"("Ext", "Value") VALUES ('xltx', 'application/vnd.openxmlformats-officedocument.spreadsheetml.template');
INSERT INTO "Mime"("Ext", "Value") VALUES ('xlw', 'application/vnd.ms-excel');
INSERT INTO "Mime"("Ext", "Value") VALUES ('xml', 'text/xml');
INSERT INTO "Mime"("Ext", "Value") VALUES ('xmp', 'application/octet-stream');
INSERT INTO "Mime"("Ext", "Value") VALUES ('xmta', 'application/xml');
INSERT INTO "Mime"("Ext", "Value") VALUES ('xof', 'x-world/x-vrml');
INSERT INTO "Mime"("Ext", "Value") VALUES ('XOML', 'text/plain');
INSERT INTO "Mime"("Ext", "Value") VALUES ('xpm', 'image/x-xpixmap');
INSERT INTO "Mime"("Ext", "Value") VALUES ('xps', 'application/vnd.ms-xpsdocument');
INSERT INTO "Mime"("Ext", "Value") VALUES ('xrm-ms', 'text/xml');
INSERT INTO "Mime"("Ext", "Value") VALUES ('xsc', 'application/xml');
INSERT INTO "Mime"("Ext", "Value") VALUES ('xsd', 'text/xml');
INSERT INTO "Mime"("Ext", "Value") VALUES ('xsf', 'text/xml');
INSERT INTO "Mime"("Ext", "Value") VALUES ('xsl', 'text/xml');
INSERT INTO "Mime"("Ext", "Value") VALUES ('xslt', 'text/xml');
INSERT INTO "Mime"("Ext", "Value") VALUES ('xsn', 'application/octet-stream');
INSERT INTO "Mime"("Ext", "Value") VALUES ('xss', 'application/xml');
INSERT INTO "Mime"("Ext", "Value") VALUES ('xspf', 'application/xspf+xml');
INSERT INTO "Mime"("Ext", "Value") VALUES ('xtp', 'application/octet-stream');
INSERT INTO "Mime"("Ext", "Value") VALUES ('xwd', 'image/x-xwindowdump');
INSERT INTO "Mime"("Ext", "Value") VALUES ('z', 'application/x-compress');
INSERT INTO "Mime"("Ext", "Value") VALUES ('zip', 'application/zip');
INSERT INTO "Module"("Id", "Number", "Name", "Code", "Icon", "Version", "Remarks", "ApiRequestCount") VALUES ('39F498A8-AE7B-049F-C78A-E16941E70FC5', 0, '权限管理', 'Admin', 'permission', '1.9.24', '权限管理模块用于身份认证以及授权等功能', 0);
INSERT INTO "Role"("Id", "Name", "Remarks", "IsSpecified", "CreatedTime", "CreatedBy", "ModifiedTime", "ModifiedBy", "Deleted", "DeletedTime", "DeletedBy") VALUES ('39F08CFD-8DD0-BB54-4544-C2DC43C6CA38', '超级管理员', '超级管理员', 0, '2019-09-29 10:19:21', '00000000-0000-0000-0000-000000000000', '2020-01-13 19:26:56', '39F08CFD-8E0D-771B-A2F3-2639A62CA2FA', 0, '2019-09-29 10:19:21', '00000000-0000-0000-0000-000000000000');
INSERT INTO "Role_Button"("RoleId", "PageCode", "ButtonCode") VALUES ('39F08CFD-8DD0-BB54-4544-C2DC43C6CA38', 'admin_account', 'admin_account_add');
INSERT INTO "Role_Button"("RoleId", "PageCode", "ButtonCode") VALUES ('39F08CFD-8DD0-BB54-4544-C2DC43C6CA38', 'admin_account', 'admin_account_edit');
INSERT INTO "Role_Button"("RoleId", "PageCode", "ButtonCode") VALUES ('39F08CFD-8DD0-BB54-4544-C2DC43C6CA38', 'admin_account', 'admin_account_del');
INSERT INTO "Role_Button"("RoleId", "PageCode", "ButtonCode") VALUES ('39F08CFD-8DD0-BB54-4544-C2DC43C6CA38', 'admin_account', 'admin_account_reset_password');
INSERT INTO "Role_Button"("RoleId", "PageCode", "ButtonCode") VALUES ('39F08CFD-8DD0-BB54-4544-C2DC43C6CA38', 'admin_account', 'admin_account_active');
INSERT INTO "Role_Button"("RoleId", "PageCode", "ButtonCode") VALUES ('39F08CFD-8DD0-BB54-4544-C2DC43C6CA38', 'admin_auditinfo', 'admin_auditinfo_details');
INSERT INTO "Role_Button"("RoleId", "PageCode", "ButtonCode") VALUES ('39F08CFD-8DD0-BB54-4544-C2DC43C6CA38', 'admin_auditinfo', 'admin_auditinfo_export');
INSERT INTO "Role_Button"("RoleId", "PageCode", "ButtonCode") VALUES ('39F08CFD-8DD0-BB54-4544-C2DC43C6CA38', 'admin_cache', 'admin_cache_clear');
INSERT INTO "Role_Button"("RoleId", "PageCode", "ButtonCode") VALUES ('39F08CFD-8DD0-BB54-4544-C2DC43C6CA38', 'admin_file', 'admin_file_export');
INSERT INTO "Role_Button"("RoleId", "PageCode", "ButtonCode") VALUES ('39F08CFD-8DD0-BB54-4544-C2DC43C6CA38', 'admin_file', 'admin_file_del');
INSERT INTO "Role_Button"("RoleId", "PageCode", "ButtonCode") VALUES ('39F08CFD-8DD0-BB54-4544-C2DC43C6CA38', 'admin_file', 'admin_file_harddel');
INSERT INTO "Role_Button"("RoleId", "PageCode", "ButtonCode") VALUES ('39F08CFD-8DD0-BB54-4544-C2DC43C6CA38', 'admin_log_login', 'admin_log_login_export');
INSERT INTO "Role_Button"("RoleId", "PageCode", "ButtonCode") VALUES ('39F08CFD-8DD0-BB54-4544-C2DC43C6CA38', 'admin_menu', 'admin_menu_add');
INSERT INTO "Role_Button"("RoleId", "PageCode", "ButtonCode") VALUES ('39F08CFD-8DD0-BB54-4544-C2DC43C6CA38', 'admin_menu', 'admin_menu_edit');
INSERT INTO "Role_Button"("RoleId", "PageCode", "ButtonCode") VALUES ('39F08CFD-8DD0-BB54-4544-C2DC43C6CA38', 'admin_menu', 'admin_menu_del');
INSERT INTO "Role_Button"("RoleId", "PageCode", "ButtonCode") VALUES ('39F08CFD-8DD0-BB54-4544-C2DC43C6CA38', 'admin_menu', 'admin_menu_sort');
INSERT INTO "Role_Button"("RoleId", "PageCode", "ButtonCode") VALUES ('39F08CFD-8DD0-BB54-4544-C2DC43C6CA38', 'admin_mime', 'admin_mime_add');
INSERT INTO "Role_Button"("RoleId", "PageCode", "ButtonCode") VALUES ('39F08CFD-8DD0-BB54-4544-C2DC43C6CA38', 'admin_mime', 'admin_mime_edit');
INSERT INTO "Role_Button"("RoleId", "PageCode", "ButtonCode") VALUES ('39F08CFD-8DD0-BB54-4544-C2DC43C6CA38', 'admin_mime', 'admin_mime_del');
INSERT INTO "Role_Button"("RoleId", "PageCode", "ButtonCode") VALUES ('39F08CFD-8DD0-BB54-4544-C2DC43C6CA38', 'admin_role', 'admin_role_add');
INSERT INTO "Role_Button"("RoleId", "PageCode", "ButtonCode") VALUES ('39F08CFD-8DD0-BB54-4544-C2DC43C6CA38', 'admin_role', 'admin_role_edit');
INSERT INTO "Role_Button"("RoleId", "PageCode", "ButtonCode") VALUES ('39F08CFD-8DD0-BB54-4544-C2DC43C6CA38', 'admin_role', 'admin_role_del');
INSERT INTO "Role_Button"("RoleId", "PageCode", "ButtonCode") VALUES ('39F08CFD-8DD0-BB54-4544-C2DC43C6CA38', 'admin_role', 'admin_role_bind_menus');
INSERT INTO "Role_Button"("RoleId", "PageCode", "ButtonCode") VALUES ('39F08CFD-8DD0-BB54-4544-C2DC43C6CA38', 'admin_role', 'admin_role_bind_pages');
INSERT INTO "Role_Button"("RoleId", "PageCode", "ButtonCode") VALUES ('39F08CFD-8DD0-BB54-4544-C2DC43C6CA38', 'admin_role', 'admin_role_bind_platform');
INSERT INTO "Role_Menu"("RoleId", "MenuId") VALUES ('39F08CFD-8DD0-BB54-4544-C2DC43C6CA38', '39F3C49C-400A-B33D-0C8F-E878AAABA954');
INSERT INTO "Role_Menu"("RoleId", "MenuId") VALUES ('39F08CFD-8DD0-BB54-4544-C2DC43C6CA38', '39F3C49C-D5DC-90A5-6CC3-B3A0B9040643');
INSERT INTO "Role_Menu"("RoleId", "MenuId") VALUES ('39F08CFD-8DD0-BB54-4544-C2DC43C6CA38', '39F3C49C-ED14-45E0-718C-7D650D850143');
INSERT INTO "Role_Menu"("RoleId", "MenuId") VALUES ('39F08CFD-8DD0-BB54-4544-C2DC43C6CA38', '39F3C49C-FFC8-9DE6-77EB-0FE0A8364F8C');
INSERT INTO "Role_Menu"("RoleId", "MenuId") VALUES ('39F08CFD-8DD0-BB54-4544-C2DC43C6CA38', '39F3C49D-0EB2-662F-2A0D-706F41140D12');
INSERT INTO "Role_Menu"("RoleId", "MenuId") VALUES ('39F08CFD-8DD0-BB54-4544-C2DC43C6CA38', '39F3C49C-1756-9047-34B5-6DCFADEFE28D');
INSERT INTO "Role_Menu"("RoleId", "MenuId") VALUES ('39F08CFD-8DD0-BB54-4544-C2DC43C6CA38', '39F3C49C-8CCC-2A54-DAC7-B5DD6503D91A');
INSERT INTO "Role_Menu"("RoleId", "MenuId") VALUES ('39F08CFD-8DD0-BB54-4544-C2DC43C6CA38', '39F4D6D2-3508-0CFC-205E-7BD7B887F3F4');
INSERT INTO "Role_Menu"("RoleId", "MenuId") VALUES ('39F08CFD-8DD0-BB54-4544-C2DC43C6CA38', '39F3C49C-ADF2-D90F-9626-99ACECC76C37');
INSERT INTO "Role_Menu"("RoleId", "MenuId") VALUES ('39F08CFD-8DD0-BB54-4544-C2DC43C6CA38', '39F3C49C-9EF2-C04B-FC63-5CDC9811C506');
INSERT INTO "Role_Menu"("RoleId", "MenuId") VALUES ('39F08CFD-8DD0-BB54-4544-C2DC43C6CA38', '39F4D6B4-CB9E-0BA7-E46E-442013F4D8BA');
INSERT INTO "Role_Menu"("RoleId", "MenuId") VALUES ('39F08CFD-8DD0-BB54-4544-C2DC43C6CA38', '39F4C72F-10A9-FC03-FCBD-B6A8A29A3709');
INSERT INTO "Role_Menu"("RoleId", "MenuId") VALUES ('39F08CFD-8DD0-BB54-4544-C2DC43C6CA38', '39F4C72F-5F6B-1879-7D4C-7915512406E9');
INSERT INTO "Role_Menu"("RoleId", "MenuId") VALUES ('39F08CFD-8DD0-BB54-4544-C2DC43C6CA38', '39F4C72F-6E11-71DE-E74B-67B7E152B442');
INSERT INTO "Role_Menu"("RoleId", "MenuId") VALUES ('39F08CFD-8DD0-BB54-4544-C2DC43C6CA38', '39F3C49B-5FC3-33BE-0FCD-652929D9EA73');
INSERT INTO "Role_Menu"("RoleId", "MenuId") VALUES ('39F08CFD-8DD0-BB54-4544-C2DC43C6CA38', '39F3C49B-D757-EA18-E9C4-D9C768F77512');
INSERT INTO "Role_Page"("RoleId", "PageCode") VALUES ('39F08CFD-8DD0-BB54-4544-C2DC43C6CA38', 'admin_account');
INSERT INTO "Role_Page"("RoleId", "PageCode") VALUES ('39F08CFD-8DD0-BB54-4544-C2DC43C6CA38', 'admin_auditinfo');
INSERT INTO "Role_Page"("RoleId", "PageCode") VALUES ('39F08CFD-8DD0-BB54-4544-C2DC43C6CA38', 'admin_cache');
INSERT INTO "Role_Page"("RoleId", "PageCode") VALUES ('39F08CFD-8DD0-BB54-4544-C2DC43C6CA38', 'admin_config');
INSERT INTO "Role_Page"("RoleId", "PageCode") VALUES ('39F08CFD-8DD0-BB54-4544-C2DC43C6CA38', 'admin_file');
INSERT INTO "Role_Page"("RoleId", "PageCode") VALUES ('39F08CFD-8DD0-BB54-4544-C2DC43C6CA38', 'home');
INSERT INTO "Role_Page"("RoleId", "PageCode") VALUES ('39F08CFD-8DD0-BB54-4544-C2DC43C6CA38', 'admin_icon');
INSERT INTO "Role_Page"("RoleId", "PageCode") VALUES ('39F08CFD-8DD0-BB54-4544-C2DC43C6CA38', 'admin_log_login');
INSERT INTO "Role_Page"("RoleId", "PageCode") VALUES ('39F08CFD-8DD0-BB54-4544-C2DC43C6CA38', 'admin_menu');
INSERT INTO "Role_Page"("RoleId", "PageCode") VALUES ('39F08CFD-8DD0-BB54-4544-C2DC43C6CA38', 'admin_mime');
INSERT INTO "Role_Page"("RoleId", "PageCode") VALUES ('39F08CFD-8DD0-BB54-4544-C2DC43C6CA38', 'admin_module');
INSERT INTO "Role_Page"("RoleId", "PageCode") VALUES ('39F08CFD-8DD0-BB54-4544-C2DC43C6CA38', 'admin_role');
INSERT INTO "Role_Permission"("RoleId", "Platform", "PermissionCode") VALUES ('39F08CFD-8DD0-BB54-4544-C2DC43C6CA38', 0, 'admin_account_query_get');
INSERT INTO "Role_Permission"("RoleId", "Platform", "PermissionCode") VALUES ('39F08CFD-8DD0-BB54-4544-C2DC43C6CA38', 0, 'admin_account_add_post');
INSERT INTO "Role_Permission"("RoleId", "Platform", "PermissionCode") VALUES ('39F08CFD-8DD0-BB54-4544-C2DC43C6CA38', 0, 'admin_account_edit_get');
INSERT INTO "Role_Permission"("RoleId", "Platform", "PermissionCode") VALUES ('39F08CFD-8DD0-BB54-4544-C2DC43C6CA38', 0, 'admin_account_update_post');
INSERT INTO "Role_Permission"("RoleId", "Platform", "PermissionCode") VALUES ('39F08CFD-8DD0-BB54-4544-C2DC43C6CA38', 0, 'admin_account_delete_delete');
INSERT INTO "Role_Permission"("RoleId", "Platform", "PermissionCode") VALUES ('39F08CFD-8DD0-BB54-4544-C2DC43C6CA38', 0, 'admin_account_resetpassword_post');
INSERT INTO "Role_Permission"("RoleId", "Platform", "PermissionCode") VALUES ('39F08CFD-8DD0-BB54-4544-C2DC43C6CA38', 0, 'admin_account_active_post');
INSERT INTO "Role_Permission"("RoleId", "Platform", "PermissionCode") VALUES ('39F08CFD-8DD0-BB54-4544-C2DC43C6CA38', 0, 'admin_auditinfo_query_get');
INSERT INTO "Role_Permission"("RoleId", "Platform", "PermissionCode") VALUES ('39F08CFD-8DD0-BB54-4544-C2DC43C6CA38', 0, 'admin_auditinfo_details_get');
INSERT INTO "Role_Permission"("RoleId", "Platform", "PermissionCode") VALUES ('39F08CFD-8DD0-BB54-4544-C2DC43C6CA38', 0, 'admin_auditinfo_export_post');
INSERT INTO "Role_Permission"("RoleId", "Platform", "PermissionCode") VALUES ('39F08CFD-8DD0-BB54-4544-C2DC43C6CA38', 0, 'admin_cache_query_get');
INSERT INTO "Role_Permission"("RoleId", "Platform", "PermissionCode") VALUES ('39F08CFD-8DD0-BB54-4544-C2DC43C6CA38', 0, 'admin_cache_clear_delete');
INSERT INTO "Role_Permission"("RoleId", "Platform", "PermissionCode") VALUES ('39F08CFD-8DD0-BB54-4544-C2DC43C6CA38', 0, 'admin_config_edit_get');
INSERT INTO "Role_Permission"("RoleId", "Platform", "PermissionCode") VALUES ('39F08CFD-8DD0-BB54-4544-C2DC43C6CA38', 0, 'admin_config_update_post');
INSERT INTO "Role_Permission"("RoleId", "Platform", "PermissionCode") VALUES ('39F08CFD-8DD0-BB54-4544-C2DC43C6CA38', 0, 'admin_config_UploadLogo_post');
INSERT INTO "Role_Permission"("RoleId", "Platform", "PermissionCode") VALUES ('39F08CFD-8DD0-BB54-4544-C2DC43C6CA38', 0, 'admin_config_LogoUrl_get');
INSERT INTO "Role_Permission"("RoleId", "Platform", "PermissionCode") VALUES ('39F08CFD-8DD0-BB54-4544-C2DC43C6CA38', 0, 'admin_config_Descriptors_get');
INSERT INTO "Role_Permission"("RoleId", "Platform", "PermissionCode") VALUES ('39F08CFD-8DD0-BB54-4544-C2DC43C6CA38', 0, 'admin_file_query_get');
INSERT INTO "Role_Permission"("RoleId", "Platform", "PermissionCode") VALUES ('39F08CFD-8DD0-BB54-4544-C2DC43C6CA38', 0, 'admin_file_export_get');
INSERT INTO "Role_Permission"("RoleId", "Platform", "PermissionCode") VALUES ('39F08CFD-8DD0-BB54-4544-C2DC43C6CA38', 0, 'admin_file_delete_delete');
INSERT INTO "Role_Permission"("RoleId", "Platform", "PermissionCode") VALUES ('39F08CFD-8DD0-BB54-4544-C2DC43C6CA38', 0, 'admin_file_hardDelete_delete');
INSERT INTO "Role_Permission"("RoleId", "Platform", "PermissionCode") VALUES ('39F08CFD-8DD0-BB54-4544-C2DC43C6CA38', 0, 'admin_log_login_get');
INSERT INTO "Role_Permission"("RoleId", "Platform", "PermissionCode") VALUES ('39F08CFD-8DD0-BB54-4544-C2DC43C6CA38', 0, 'admin_log_loginexport_post');
INSERT INTO "Role_Permission"("RoleId", "Platform", "PermissionCode") VALUES ('39F08CFD-8DD0-BB54-4544-C2DC43C6CA38', 0, 'admin_menu_query_get');
INSERT INTO "Role_Permission"("RoleId", "Platform", "PermissionCode") VALUES ('39F08CFD-8DD0-BB54-4544-C2DC43C6CA38', 0, 'admin_menu_tree_get');
INSERT INTO "Role_Permission"("RoleId", "Platform", "PermissionCode") VALUES ('39F08CFD-8DD0-BB54-4544-C2DC43C6CA38', 0, 'admin_menu_add_post');
INSERT INTO "Role_Permission"("RoleId", "Platform", "PermissionCode") VALUES ('39F08CFD-8DD0-BB54-4544-C2DC43C6CA38', 0, 'admin_menu_edit_Get');
INSERT INTO "Role_Permission"("RoleId", "Platform", "PermissionCode") VALUES ('39F08CFD-8DD0-BB54-4544-C2DC43C6CA38', 0, 'admin_menu_update_post');
INSERT INTO "Role_Permission"("RoleId", "Platform", "PermissionCode") VALUES ('39F08CFD-8DD0-BB54-4544-C2DC43C6CA38', 0, 'admin_menu_delete_delete');
INSERT INTO "Role_Permission"("RoleId", "Platform", "PermissionCode") VALUES ('39F08CFD-8DD0-BB54-4544-C2DC43C6CA38', 0, 'admin_menu_sort_get');
INSERT INTO "Role_Permission"("RoleId", "Platform", "PermissionCode") VALUES ('39F08CFD-8DD0-BB54-4544-C2DC43C6CA38', 0, 'admin_menu_sort_post');
INSERT INTO "Role_Permission"("RoleId", "Platform", "PermissionCode") VALUES ('39F08CFD-8DD0-BB54-4544-C2DC43C6CA38', 0, 'admin_mime_query_get');
INSERT INTO "Role_Permission"("RoleId", "Platform", "PermissionCode") VALUES ('39F08CFD-8DD0-BB54-4544-C2DC43C6CA38', 0, 'admin_mime_add_post');
INSERT INTO "Role_Permission"("RoleId", "Platform", "PermissionCode") VALUES ('39F08CFD-8DD0-BB54-4544-C2DC43C6CA38', 0, 'admin_mime_edit_get');
INSERT INTO "Role_Permission"("RoleId", "Platform", "PermissionCode") VALUES ('39F08CFD-8DD0-BB54-4544-C2DC43C6CA38', 0, 'admin_mime_update_post');
INSERT INTO "Role_Permission"("RoleId", "Platform", "PermissionCode") VALUES ('39F08CFD-8DD0-BB54-4544-C2DC43C6CA38', 0, 'admin_mime_delete_delete');
INSERT INTO "Role_Permission"("RoleId", "Platform", "PermissionCode") VALUES ('39F08CFD-8DD0-BB54-4544-C2DC43C6CA38', 0, 'admin_module_query_get');
INSERT INTO "Role_Permission"("RoleId", "Platform", "PermissionCode") VALUES ('39F08CFD-8DD0-BB54-4544-C2DC43C6CA38', 0, 'admin_permission_query_get');
INSERT INTO "Role_Permission"("RoleId", "Platform", "PermissionCode") VALUES ('39F08CFD-8DD0-BB54-4544-C2DC43C6CA38', 0, 'admin_permission_querybycodes_get');
INSERT INTO "Role_Permission"("RoleId", "Platform", "PermissionCode") VALUES ('39F08CFD-8DD0-BB54-4544-C2DC43C6CA38', 0, 'admin_role_query_get');
INSERT INTO "Role_Permission"("RoleId", "Platform", "PermissionCode") VALUES ('39F08CFD-8DD0-BB54-4544-C2DC43C6CA38', 0, 'admin_role_add_post');
INSERT INTO "Role_Permission"("RoleId", "Platform", "PermissionCode") VALUES ('39F08CFD-8DD0-BB54-4544-C2DC43C6CA38', 0, 'admin_role_edit_get');
INSERT INTO "Role_Permission"("RoleId", "Platform", "PermissionCode") VALUES ('39F08CFD-8DD0-BB54-4544-C2DC43C6CA38', 0, 'admin_role_update_post');
INSERT INTO "Role_Permission"("RoleId", "Platform", "PermissionCode") VALUES ('39F08CFD-8DD0-BB54-4544-C2DC43C6CA38', 0, 'admin_role_delete_delete');
INSERT INTO "Role_Permission"("RoleId", "Platform", "PermissionCode") VALUES ('39F08CFD-8DD0-BB54-4544-C2DC43C6CA38', 0, 'admin_role_BindMenus_get');
INSERT INTO "Role_Permission"("RoleId", "Platform", "PermissionCode") VALUES ('39F08CFD-8DD0-BB54-4544-C2DC43C6CA38', 0, 'admin_role_BindMenus_post');
INSERT INTO "Role_Permission"("RoleId", "Platform", "PermissionCode") VALUES ('39F08CFD-8DD0-BB54-4544-C2DC43C6CA38', 0, 'admin_role_BindPages_get');
INSERT INTO "Role_Permission"("RoleId", "Platform", "PermissionCode") VALUES ('39F08CFD-8DD0-BB54-4544-C2DC43C6CA38', 0, 'admin_role_BindPages_post');
INSERT INTO "Role_Permission"("RoleId", "Platform", "PermissionCode") VALUES ('39F08CFD-8DD0-BB54-4544-C2DC43C6CA38', 0, 'admin_permission_tree_get');
INSERT INTO "Role_Permission"("RoleId", "Platform", "PermissionCode") VALUES ('39F08CFD-8DD0-BB54-4544-C2DC43C6CA38', 0, 'admin_role_BindPlatformPermissions_get');
INSERT INTO "Role_Permission"("RoleId", "Platform", "PermissionCode") VALUES ('39F08CFD-8DD0-BB54-4544-C2DC43C6CA38', 0, 'admin_role_BindPlatformPermissions_post');
